### ISSUE TITLE
ngn-windows is only supported on Windows.

### ISSUE THREAD

**Issue by ilovepumpkin** [cytle/wechat_web_devtools#10]
我之前做了一个微信小程序，但是最近出现了奇怪的问题，所以根据更新步骤升级了一下这个开发工具。

第一次启动的时候，看到了这个提示框。我的小程序里发送所有网络请求一直timeout。
![image](https://cloud.githubusercontent.com/assets/11310645/26537893/7e7cca24-4475-11e7-9617-08648b36d9b4.png)

于是我关了再次打开，命令行里显示如下错误。窗口里则一直显示“更新中...”
```
ilovepumpkin@ruige:~/git/wechat_web_devtools$ ./bin/wxdt
/home/ilovepumpkin/git/wechat_web_devtools

/home/ilovepumpkin/git/wechat_web_devtools/package.nw/node_modules/node-windows/lib/node-windows.js:19
  throw 'ngn-windows is only supported on Windows.';
  ^
ngn-windows is only supported on Windows.
```
![image](https://cloud.githubusercontent.com/assets/11310645/26537967/e5247bdc-4475-11e7-8418-55761e34938d.png)

我的系统是Ubuntu 16.04。

**Comment by cytle** [comment]
和https://github.com/cytle/wechat_web_devtools/issues/5 相同，现在已经更新到最新版本v0.17.172600

`git pull`即可
