### ISSUE TITLE
更新packages.nw

### ISSUE THREAD

**Issue by laeo** [cytle/wechat_web_devtools#100]
在deepin linux下，会无法找到wine这个可执行程序，建议使用 `7z` 命令行工具来解压下载好的新版程序的exe文件，然后将解压出来的数据中的packages.nw目录直接拷贝即可。希望能够采纳谢谢。

**Comment by cytle** [comment]
哈哈，还有这操作，我研究下

**Comment by imknown** [comment]
Windows 上试了一下, 好像确实 安装完毕的 和 直接解压出来的 packages.nw 一样..

**Comment by cytle** [comment]
新版的安装包目录结构和旧的差很大.. 特别package.nw这个目录都不见了..用7z解压后目录和设想的不一致..

@imknown @laeo 有什么见解吗

**Comment by laeo** [comment]
刚刚解压看了下，package.nw被移动到 `/$APPDATA/Tencent/微信web开发者工具/` 目录下了

**Comment by cytle** [comment]
最新`1.02.1805181`版本的，解压后三个乱码文件夹，一个是nwjs，另外两个不明用途。。
![image](https://user-images.githubusercontent.com/5120505/40278493-6baf79d4-5c64-11e8-9de6-f61afd39a556.png)

**Comment by imknown** [comment]
Windows 解压是这样子的

![qq 20180521104855](https://user-images.githubusercontent.com/5681447/40288304-296cb48e-5ce5-11e8-8576-fadd8cd91fac.png)

---

安装日志 (最后面可能漏了几句)
[wechat_devtools_1.02.1805181_x64_install_log.txt](https://github.com/cytle/wechat_web_devtools/files/2021055/wechat_devtools_1.02.1805181_x64_install_log.txt)

**Comment by cytle** [comment]
已经使用7z解压来替代wine安装,  https://github.com/cytle/wechat_web_devtools/pull/150
Thank you, @imknown @laeo
