### ISSUE TITLE
编译wxml文件错误，软件包 wine-binfmt 没有可安装候选

### ISSUE THREAD

**Issue by YanYuanFE** [cytle/wechat_web_devtools#101]
![image](https://user-images.githubusercontent.com/17774285/38910412-c165b85c-42fb-11e8-8efb-e3e22099f772.png)
![image](https://user-images.githubusercontent.com/17774285/38910433-d49b65d4-42fb-11e8-8f64-cad7a47efc32.png)

OS：Ubuntu16.04

**Comment by YanYuanFE** [comment]
wine：3.6

**Comment by imknown** [comment]
https://bugs.launchpad.net/ubuntu/+source/wine/+bug/1637848/comments/3
emmmmm.... 16.10

**Comment by hefengly** [comment]
遇到这个问题了，有什么解决的办法吗

**Comment by hefengly** [comment]
linux 是16.04

**Comment by zgq354** [comment]
我的系统是 Ubuntu 16.04 LTS，同样也遇到了这个问题，以下是我整理出来的解决问题的过程：

参考这个 [Adding binfmt configuration to official Wine packages](https://www.winehq.org/pipermail/wine-devel/2016-August/114478.html)，手动添加一个解析 Windows 的 exe 的 binfmt 配置

```
vim /usr/share/binfmts/wine
```
内容填入
```
package wine
interpreter /usr/bin/wine
magic MZ
```
保存退出，更新一下配置就好了
```
sudo update-binfmts --import wine
```
