### ISSUE TITLE
nwjs下载网址变更

### ISSUE THREAD

**Issue by fushenguang** [cytle/wechat_web_devtools#102]
nwjs下载网址的协议由https =>http, 正确的地址: http://dl.nwjs.io/v0.24.4/nwjs-sdk-v0.24.4-linux-x64.tar.gz,

**Comment by imknown** [comment]
https://github.com/cytle/wechat_web_devtools/blob/master/bin/update_nwjs.sh#L4-L17

你的网络可能有问题, 我这里 https 可用...

**Comment by fushenguang** [comment]
网络问题???好吧，我这边的确没法访问https://dl.nwjs.io，改用http协议就好了，碰到类似问题的朋友可以试下（也是这两天出现的该问题）
