### ISSUE TITLE
软件标题显示乱码

### ISSUE THREAD

**Issue by 13568810905** [cytle/wechat_web_devtools#103]
可以看到web，但是其他的文字都显示的乱码，ubuntu 17.1 安装了中文语言包应该不是不支持中文的情况，其他软件都是正常的

**Comment by imknown** [comment]
你先看看你本地 `locale` 咋配置的呗...

**Comment by 13568810905** [comment]
![2018-04-24 10-32-57](https://user-images.githubusercontent.com/34223095/39162982-fbc16a7e-47aa-11e8-8be9-3449513c6daa.png)
是这个吗
zhengweiyi@weiyi-latitude-3330:~$ locale
LANG=zh_CN.UTF-8
LANGUAGE=zh_CN:zh
LC_CTYPE="zh_CN.UTF-8"
LC_NUMERIC="zh_CN.UTF-8"
LC_TIME="zh_CN.UTF-8"
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY="zh_CN.UTF-8"
LC_MESSAGES="zh_CN.UTF-8"
LC_PAPER="zh_CN.UTF-8"
LC_NAME="zh_CN.UTF-8"
LC_ADDRESS="zh_CN.UTF-8"
LC_TELEPHONE="zh_CN.UTF-8"
LC_MEASUREMENT="zh_CN.UTF-8"
LC_IDENTIFICATION="zh_CN.UTF-8"
LC_ALL=
zhengweiyi@weiyi-latitude-3330:~$ 
@imknown

**Comment by imknown** [comment]
启动前 加上 export LC_ALL=zh_CN.utf-8 试试

**Comment by cytle** [comment]
@13568810905 解决了吗？

**Comment by jessieeeee** [comment]
我也是这个问题，加上export LC_ALL=zh_CN.utf-8仍然无效

**Comment by jasonzhl** [comment]
麻烦问下，这个问题解决了吗？我在debian上安装也出现了一样的问题， 请教怎么解决的？

**Comment by Xchuanshuo** [comment]
同样　进去显示正常　就是状态栏的标题显示乱码

**Comment by SaxonZhang2** [comment]
ubuntu 18.04 ,就只有标题有乱码， 其他地方显示都正常。

**Comment by 04swjxy** [comment]
ubuntu 18.04,标题乱码, 导致桌面图标无法正常显示

**Comment by jessieeeee** [comment]
还不如直接改成英文标题，我这是英文系统装了中文语言包还是乱码

**Comment by milkysilk** [comment]
你们更新一下最新的看看，我用的是arch（忽略图标和chrome标签......），英文环境

![image](https://user-images.githubusercontent.com/31210021/43668394-47c0535a-97af-11e8-8452-06cf9866eb3b.png)

我上次安装的时候有乱码，现在应该没有了

**Comment by sdzbzjh** [comment]
@04swjxy 麻烦问下，这个问题你解决了吗？ubuntu18.04标题乱码的问题

**Comment by jasonzhl** [comment]
没有解决， 我用的是debian。 现在还是乱码呢。


________________________________
发件人: Vincent.Zh <notifications@github.com>
发送时间: 2018年8月11日 13:10
收件人: cytle/wechat_web_devtools
抄送: jasonzhl; Comment
主题: Re: [cytle/wechat_web_devtools] 软件标题显示乱码 (#103)


@04swjxy<https://github.com/04swjxy> 麻烦问下，这个问题你解决了吗？ubuntu18.04标题乱码的问题

―

**Comment by adminzhao** [comment]
Ubuntu 18.04 同样只是标题乱码 我程序名字都是英文 很奇怪为什么会有乱码

**Comment by tankgit** [comment]
@13568810905 @jessieeeee @jasonzhl @sdzbzjh @adminzhao 可能的解决方法（我的有效, ubuntu18.04）
1. 编辑软件目录下的`package.nw/package.json`，修改`name`的值为英文，比如我改成了`wechat-dev`
2. 这时候你再运行，标题栏的乱码已经解决，但是你原先的配置全部重置了，此时找到`~/.config`目录下有一个叫`微信web开发者工具`的文件夹，修改为你第一步改的英文名，done.

另外，你的如果发现打开的程序会单另启动一个窗口，不以App菜单里的窗口启动，像这样：
![image](https://user-images.githubusercontent.com/7694464/44827804-627fd380-ac47-11e8-94fa-d7de7abdcbbc.png)（第一个和第四个图标）
修改`~/.local/share/applications/wechat_dev_tools.desktop`，加一项`StartupWMClass=wechat-dev`，就统一了，如果不行，请把所有跟这个软件有关的name的值，包括二进制程序文件名，以及`StartupWMClass`的值，全部改成同一个名字试试。

**Comment by jessieeeee** [comment]
改英文标题这个办法试过，确实是有效的，中文标题暂时还不知道怎么解决，更新以后还要再改一次

**Comment by cytle** [comment]
如@tankgit 所讲，改软件名字会生成新的配置文件夹，~/.config/{开发者工具}`，造成之前的项目和配置丢失，还没想到好的办法

**Comment by sumic** [comment]
按照@tankgit的方法完没解决，good job.

**Comment by cytle** [comment]
现在工具名字改成`wechat_dev_tools`应该没这个问题了
