### ISSUE TITLE
安装最新版1.02.1805080失败

### ISSUE THREAD

**Issue by tengqian** [cytle/wechat_web_devtools#110]
最新版安装之后没有package.nw升级失败
以下是wine安装之后的目录
![_ _20180509160156](https://user-images.githubusercontent.com/25736019/39803085-7b6b7708-53a2-11e8-866a-fe5cfaf88e6e.png)

以下是升级错误信息
![_deepin-terminal_20180509155840](https://user-images.githubusercontent.com/25736019/39802963-17f72f32-53a2-11e8-81ff-402012360fcb.png)

**Comment by cytle** [comment]
新版本的开发者工具，`package.nw`文件夹改在`Application Data`中了，现在升级脚本还不支持
