### ISSUE TITLE
新建新项目的时候报错

### ISSUE THREAD

**Issue by ashengtx** [cytle/wechat_web_devtools#111]
![image](https://user-images.githubusercontent.com/7556816/39861736-1a0b7d6e-5474-11e8-9d4c-e5754b59bc25.png
![screenshot from 2018-05-10 17-03-08](https://user-images.githubusercontent.com/7556816/39861762-319f40c8-5474-11e8-9265-bfd81156e231.png)

**Comment by cytle** [comment]
1. 完全关闭，重新启动。
2. 提供控制台错误截图
