### ISSUE TITLE
请求作者升级到1.02.1804251,当前版本无法先WXML节点

### ISSUE THREAD

**Issue by tudoubang** [cytle/wechat_web_devtools#113]
![image](https://user-images.githubusercontent.com/8858433/40048224-4334c102-5864-11e8-9b60-df2e05c568fa.png)
非常感谢!!:+1:

@cytle :+1::+1::+1::+1::+1:

**Comment by imknown** [comment]
我的 nwjs 一直用的 官网最新的

**Comment by tudoubang** [comment]
**1.02.1804251**是可以用的,但是刚在将**1.02.1805150**package.nw替换的时候就会报错
![image](https://user-images.githubusercontent.com/8858433/40155916-cb1ec27e-59c8-11e8-93e0-c01e662aa723.png)
正在想办法解决中
@imknown

**Comment by tudoubang** [comment]
### 使用nwjs-sdk-v0.30.4
![image](https://user-images.githubusercontent.com/8858433/40156329-7605b07e-59cb-11e8-959a-6f3b5f255fd1.png)
 
![image](https://user-images.githubusercontent.com/8858433/40156337-8000837e-59cb-11e8-951b-1e60cfca390d.png)

大概是开发者工具的bug吧[社区问题](https://developers.weixin.qq.com/blogdetail?action=get_post_info&lang=zh_CN&token=1095249803&docid=0002ae18dd4980cc37c657e8456001)

**Comment by cytle** [comment]
@tudoubang v1.02.1805150 版本的确有问题，你能推 v1.02.1804251 上来吗

**Comment by tudoubang** [comment]
@cytle 可以的,具体怎么推我没有权限

**Comment by cytle** [comment]
@tudoubang 先fork，然后开个pullrequest
