### ISSUE TITLE
运行./bin/wxdt时候报错 libgconf-2.so.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Park-Allen** [cytle/wechat_web_devtools#117]
具体报错内容如下./nw: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
这时候sudo apt install libgconf2-4 
再运行./bin/wxdt
完美

**Comment by cytle** [comment]
解决了？

**Comment by Park-Allen** [comment]
有个问题我点远程调试的时候Error: node-sync-ipc is broken.
