### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by ooobsidian** [cytle/wechat_web_devtools#119]
![](https://ws1.sinaimg.cn/large/006rvSvvgy1frl8pn5x5fj30lk0izjtk.jpg)
![](https://ws1.sinaimg.cn/large/006rvSvvgy1frl8nds19tj30sh0inq3w.jpg)
按照mpvue官方文档的 "五分钟快速上手" 的教程一步步来，为什么会出现这个问题？
应该不是端口问题。
本人用的是deepin系统。

**Comment by cytle** [comment]
嗯，试下完全推出开发者工具再打开一次

**Comment by ooobsidian** [comment]
![](https://ws1.sinaimg.cn/large/006rvSvvgy1frl8u80020j30sg0hv3yx.jpg)
刚打开就什么都没有，过较长的时间才会出现报错（第一次评论的那张图等了很久才出现的），现在重启之后还是没有。

**Comment by cytle** [comment]
参考 https://github.com/cytle/wechat_web_devtools/issues/66#issuecomment-368434141 看看是不是wine有问题

**Comment by ooobsidian** [comment]
谢谢作者啊！终于成功解决啦！～
