### ISSUE TITLE
运行期间不断报错

### ISSUE THREAD

**Issue by liaosimin** [cytle/wechat_web_devtools#120]
在终端启动的，终端报错：
(nw:12581): dconf-WARNING **: failed to commit changes to dconf: 对地址 disabled: 的未知或不支持的传输 disabled
启动后的软件弹窗显示：
“小程序重启耗时过久，请确认业务逻辑中是否有复杂运算，或者死循环”

**Comment by joyme123** [comment]
我这里也是，deepin的系统。之前一台笔记本是可以的，换了新的笔记本就不行了。有可能是最近的更新导致的

**Comment by liaosimin** [comment]
我的也是deepin系统，难道是只有deepin有这个问题？之前的deepin安装的英文版，就不段弹窗，没法用。换一台笔记本，装的是中文版deepin就可以了。

**Comment by joyme123** [comment]
看了一下报错，是wine的问题。按照这个项目的readme中的`wcc 和 wcsc 编译错误`的解决方法处理即可。

```
sudo apt-get install wine-binfmt
sudo update-binfmts --import /usr/share/binfmts/wine
```

**Comment by jhs1873** [comment]
@joyme123 感谢。实测有效～送你fafa
