### ISSUE TITLE
wcc.exe: 无法执行二进制文件？

### ISSUE THREAD

**Issue by run27017** [cytle/wechat_web_devtools#123]
首先声明下我的系统：

- openSUSE 42.3
- wine 3.9

使用如下步骤安装：

    git clone ...
    cd ...
    ./bin/wxdt install
    ./bin/wxdt

扫码登录，然后打开项目后出现如下的错误：

![default](https://user-images.githubusercontent.com/16550290/41033678-fc8badf8-69b9-11e8-9d15-88eda34da500.png)

然后我试了其他的一些方法，例如：

    WINEARCH=win32 WINEPREFIX=~/.wine32 winecfg

甚至是

    WINEARCH=win32 WINEPREFIX=~/.wine winecfg

都不奏效。在试这些方法之前我都做了如下的清理工作，以保证测试环境的干净：

1. 卸载wine、wine32等
2. `./bin/wxdt uninstall`
3. `rm -rf ~/.wine*`

首页上提供的方法：

    sudo apt-get install wine-binfmt
    sudo update-binfmts --import /usr/share/binfmts/wine

很遗憾，在openSUSE下找不到包`wine-binfmt`。

另外，我想知道我在今天（6月6日）`git clone`的项目，它的wcc.exe和wcsc.exe这两个文件是64位的还是32位的？

**Comment by cytle** [comment]
32位的

**Comment by run27017** [comment]
@cytle 那这个问题有什么方法解决的吗？关于“wcc.exe: 无法执行二进制文件”的。

**Comment by cytle** [comment]
参考 
- https://github.com/cytle/wechat_web_devtools/issues/66
- https://github.com/cytle/wechat_web_devtools/issues/56#issuecomment-371999385

![image](https://user-images.githubusercontent.com/5120505/41136029-e82b0fa4-6b06-11e8-8f6f-aef53a1fce8b.png)

**Comment by run27017** [comment]
@cytle  wine-binfmt的下载地址里没有rpm格式的包（虽然有，但openSuse不可用），我想知道wine-binfmt是必装的吗？这个无法执行二进制文件的问题的原因是什么？是因为exe是32位的吗？如果这样，其他类似的exe是不是dou没法执行？

**Comment by zsyzzx** [comment]
我的系统版本 Opensuse Tumbleweed，执行命令`echo ':DOSWin:M::MZ::/usr/bin/wine:' > /proc/sys/fs/binfmt_misc/register`后能正常运行，具体看
[ArchLinux的Wine 配置](https://wiki.archlinux.org/index.php/Wine_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)#.E4.BF.AE.E5.A4.8D_KDE_4_.E8.8F.9C.E5.8D.95.E9.97.AE.E9.A2.98)

依据文档，我在/etc/binfmt.d创建wine.conf 文件，内容为`:DOSWin:M::MZ::/usr/bin/wine:` 小程序编辑器能正常运行。
_但系统重启后，编辑器是否能正常运行还没测试_

**Comment by run27017** [comment]
@zsyzzx 你的回答完美解决了我的问题，感谢！

**Comment by run27017** [comment]
@zsyzzx 重启之后就没有效果了，如何做到开机自启动呢？

**Comment by run27017** [comment]
@zsyzzx 重启之后就没有效果了，如何做到开机自启动呢？

**Comment by Awkee** [comment]
在/etc/binfmt.d创建wine.conf 文件

```
$ ll /etc/binfmt.d/wine.conf 
-rw-r--r-- 1 root root 66 3月   4 20:59 /etc/binfmt.d/wine.conf

$ cat /etc/binfmt.d/wine.conf

# Start WINE on Windows executables
:DOSWin:M::MZ::/usr/bin/wine:

```

我在Opensuse上验证重启后是生效了的配置，不再需要每次都执行命令
`echo ':DOSWin:M::MZ::/usr/bin/wine:' > /proc/sys/fs/binfmt_misc/register`
