### ISSUE TITLE
能否实现自动打包上传应用? 

### ISSUE THREAD

**Issue by xpf0000** [cytle/wechat_web_devtools#132]
我也在研究微信的开发工具, 主要想实现像微擎那种, 拉取到微信登录的二维码, 然后用户扫码后, 直接从服务端替用户打包上传小程序,  推测是使用了官方的命令行工具, 也可能是抓的接口, 请教大神这块应该如何做?
QQ: 250881478  微信: x250881478  有时间的话麻烦指导下, 谢谢

**Comment by cytle** [comment]
官方有命令行工具，[命令行](https://developers.weixin.qq.com/miniprogram/dev/devtools/cli.html) ，你可以看下

**Comment by xpf0000** [comment]
这个命令行工具只能是在win或者mac下用, 像微擎, 是个平台, 开发者事先把小程序文件提交到微擎上,  有用户使用, 会自动替换小程序文件里的域名等配置,  然后自动帮用户打包上传

我研究了下官方的命令行工具, 是运行了一个node服务器,  
然后所有的命令 最终都是访问一个链接去实现 http://127.0.0.1:随机端口/请求  固定就是这种的
但是这个服务器必须要程序先跑起来

但是在lunix中, mac版的跑不起来, node服务器也就无法创建,  所以不清楚你的lunix版的 这块实现了没, 或者大神有没有其它解决问题的思路?
做这个主要想解决用户自定义小程序的风格和底部菜单, 用户可以定义导航栏颜色, 页面背景颜色, 底部菜单颜色, 样式, 链接到的页面等, 最终实现效果就是用户在网页上设计好自己的小程序, 在服务器上就可以根据用户的设置,自动重新生成一套小程序并打包上传

**Comment by cytle** [comment]
这个项目cli这块没有做，有时间我会去尝试下。话说回来，打包也可以部署在Windows服务器，最核心的问题在于linux怎么用cli。你的思路挺好的可以试下

**Comment by cytle** [comment]
我们公司最近也有类似的需求，因为体验版只能指定一个人上传，大家希望在一台机子上上传。

**Comment by cmideal** [comment]
大神们，这个进度如何。我看coding的也实现了在线上传，请问这个有没有思路。
我问一些的大神说是可以通过node多态，
其实最主要的问题是打包代码，我抓包其它可以抓到，但是打包这块没懂 @cytle 大神可以重点看一下这块，

**Comment by hlxabcd** [comment]
我也遇到了相同问题。我们服务器是linux。打算在linux上做每5分钟自动cli -p 并生成二维码。能够第一时间体验最新的微信小程序。但是linux cli命令行研究半天不知如何实现。望大神想想如何实现

**Comment by xiasf** [comment]
期待这个需求能实现

**Comment by halk947** [comment]
+1 期待

**Comment by cayley-hck** [comment]
+1 期待

**Comment by adreamleet** [comment]
期待这个需求能实现。。。

**Comment by mice33** [comment]
+1 期待

**Comment by cytle** [comment]
开发者工具`cli`已经可以使用，不过需要GUI环境。更新仓库，执行`./bin/cli`即可使用。
![image](https://user-images.githubusercontent.com/5120505/52988723-5547e280-343b-11e9-8d2f-aa6457598dc2.png)
