### ISSUE TITLE
程序标题乱码

### ISSUE THREAD

**Issue by notOnly20k** [cytle/wechat_web_devtools#135]
请教一下大佬manjaro linux 安装后运行正常就是标题是乱码是什么情况
![2018-07-25 09-49-08](https://user-images.githubusercontent.com/22676927/43175276-db6a8e98-8ff0-11e8-9aff-b762d1b102cc.png)

**Comment by 04swjxy** [comment]
我也是这种情况

**Comment by c0ldcat** [comment]
desktop文件里加上`StartupWMClass=crx_ikhdnebglabgeplgnhnjgldiemdflddf`
这个应用的wmclass仿佛是随机生成的... 所以可能不一样
WMClass由`xprop WM_CLASS`获得

完整:
```
[Desktop Entry]
Name=微信web开发者工具
Comment=The development tools for wechat web develop
Categories=Development;WebDevelopment;IDE;
Exec=/opt/wechat_web_devtools/bin/wxdt %U
Icon=/opt/wechat_web_devtools/dist/package.nw/static/image/logo@2x.png
Type=Application
Terminal=false
X-Desktop-File-Install-Version=0.24
StartupWMClass=crx_ikhdnebglabgeplgnhnjgldiemdflddf
```

**Comment by notOnly20k** [comment]
用你的方法解决了thanks @c0ldcat
