### ISSUE TITLE
始终提示小程序重启耗时过久

### ISSUE THREAD

**Issue by zs12593** [cytle/wechat_web_devtools#144]
打开项目后一直提示“小程序重启耗时过久，请确认业务逻辑中是否有复杂运算，或者死循环”，无论新建小程序项目还是其它正常运行的项目，系统环境 deepin 15.6

**Comment by xuliulei** [comment]
wine的问题

**Comment by zs12593** [comment]
谢谢大佬，已经解决

**Comment by ez4lionky** [comment]
> 谢谢大佬，已经解决

请问你是怎么解决的，我deepin 15.8也报错
