### ISSUE TITLE
suse上小程序编译WXML文件报错,显示无法执行二进制文件

### ISSUE THREAD

**Issue by blu10ph** [cytle/wechat_web_devtools#145]
我之前装了wine,所以直接克隆下来运行了install后就能跑了,但是打开小程序后显示
WXML 文件编译错误
.../.config/微信web开发者工具/WeappVendor/wcc.exe: 无法执行二进制文件
手动执行
wine64 ~/.config/微信web开发者工具/WeappVendor/wcc.exe
可以运行,能显示文件版本
这个报错感觉像是运行exe的时候前面没加wine,直接用linux系统执行的,因为我直接运行的时候显示的是
.../.config/微信web开发者工具/WeappVendor/wcc.exe: 无法执行二进制文件: 可执行文件格式错误

**Comment by blu10ph** [comment]
果然是这样,用root权限执行了下
echo ':exe:E::exe::/usr/bin/wine:' > /proc/sys/fs/binfmt_misc/register
就可以了,参考文档:
https://www.aliyun.com/jiaocheng/807797.html

**Comment by blu10ph** [comment]
echo ':exe:M::MZ::/usr/bin/wine:' > /proc/sys/fs/binfmt_misc/register
效果更佳.

解除注册:
echo -1 > /proc/sys/fs/binfmt_misc/exe

**Comment by Awkee** [comment]
在 `/etc/sysctl.conf `文件中添加：
```
fs.binfmt_misc.exe = enabled
fs.binfmt_misc.exe = interpreter /usr/bin/wine
fs.binfmt_misc.exe = flags: 
fs.binfmt_misc.exe = offset 0
fs.binfmt_misc.exe = magic 4d5a
```
以后重启后不需要再执行 echo 的那个命令了。
