### ISSUE TITLE
提示“小程序重启耗时过久，请确认业务逻辑中是否有复杂运算或死循环”

### ISSUE THREAD

**Issue by kakayunmu** [cytle/wechat_web_devtools#146]
我以为我项目问题，后来新建一个还是一样的错误。这是什么鬼？
项目在window 下运行正常。

**Comment by XuXianTao** [comment]
+1，debian内核的deepin系统

**Comment by XuXianTao** [comment]
看了一下小程序自己的调试信息，说是wcc编译错误
![image](https://user-images.githubusercontent.com/32198066/44739065-57cf1c80-ab29-11e8-832a-e4a43465dfc1.png)
可以尝试一下首页的方法，apt-get install wine-binfmt之后就好了

**Comment by XuXianTao** [comment]
已经解决了，就是wcc崩溃的原因，照着首页那个解决方案装一下就好了，deepin自带的wine可能不太一样






在 2018-08-31 12:24:53，"MR.Zhao" <notifications@github.com> 写道：


+1 问题解决了吗? 我也遇到这个问题了

**Comment by adminzhao** [comment]
我的问题和你的还不完全一致 我的控制台里没有报错. 绝望了.

**Comment by XuXianTao** [comment]
这个控制台看看






在 2018-08-31 12:49:50，"MR.Zhao" <notifications@github.com> 写道：


我的问题和你的还不完全一致 我的控制台里没有报错. 绝望了.

**Comment by adminzhao** [comment]
![2018-08-31 13-35-55](https://user-images.githubusercontent.com/30462974/44894544-dba02900-ad22-11e8-8647-4d021eefc8dc.png)
控制台啥都没有 原本运行正常的 今天突然就不管用了 代码也都更新了 实在是没找到原因

**Comment by XuXianTao** [comment]
噗。邮件发送图片没出来
![image](https://user-images.githubusercontent.com/32198066/44895043-0d19f400-ad25-11e8-9ded-027513f3939d.png)
应该看开发工具的控制台，不是项目的

**Comment by adminzhao** [comment]
![2018-08-31 15-43-28](https://user-images.githubusercontent.com/30462974/44899597-c46a3700-ad34-11e8-8802-4fcc85e4dd12.png)
日志是这样的

**Comment by adminzhao** [comment]
暂时解决了  我把deepin-binfmts 卸了 装了 wine-binfmts

**Comment by XuXianTao** [comment]
ok~

**Comment by adminzhao** [comment]
thanks for your help

**Comment by imknown** [comment]
也有可能是 nwjs 版本升级导致的, 删除一下 `$HOME/.config/微信web开发者工具` 试试.
**可能会丢失配置, 建议做好备份.**

参考:
- https://github.com/nwjs/nw.js/issues/5761
- https://github.com/nwjs/nw.js/issues/6188
- http://docs.nwjs.io/en/latest/References/Command%20Line%20Options/#-user-data-dir
