### ISSUE TITLE
支持Deepin系统吗

### ISSUE THREAD

**Issue by iptop** [cytle/wechat_web_devtools#148]
我用的Deepin系统,按照你的文档安装了可以用,但是安装之后发现我的深度终端没了,深度应用商店也没了

**Comment by cytle** [comment]
支持的，之前有人使用过，终端没了什么情况。。

**Comment by qwIvan** [comment]
@iptop  建议你先打包为deb包再进行安装

**Comment by milobluebell** [comment]
我就是用的deepin系统，没出现你说的这种情况。  不过我是来问如何更新软件的。^_^  @cytle

**Comment by cytle** [comment]
@milobluebell [更新到最新版](https://github.com/cytle/wechat_web_devtools#%E6%9B%B4%E6%96%B0%E5%88%B0%E6%9C%80%E6%96%B0%E7%89%88)
