### ISSUE TITLE
有的时候会卡住

### ISSUE THREAD

**Issue by yukunyi** [cytle/wechat_web_devtools#15]
有的时候会卡主，显示页面很慢，我小程序是在WebStorm里面编写的，然后通过一个js文件实时编译到输出目录，仅仅使用开发者工具运行调试，每次编译后开发者工具重新载入页面要10秒才能打开，再次打开就快了，但是一旦外部编译一次，就又卡了～～

**Comment by colorwin** [comment]
写了死循环时会直接把工具卡死...

**Comment by cytle** [comment]
编译工具是exe,这个项目是wine模拟了环境，执行会有些慢

**Comment by cytle** [comment]
属于正常问题，不会修复，没有后续提问，所以关闭。
