### ISSUE TITLE
小程序·云开发 版本支持

### ISSUE THREAD

**Issue by qiaolevip** [cytle/wechat_web_devtools#152]
目前小程序·云开发全量放开，希望@cytel 可以更新devtools，支持云开发功能。

https://mp.weixin.qq.com/debug/wxadoc/dev/wxcloud/basis/getting-started.html#%E5%85%BC%E5%AE%B9%E6%80%A7%E9%97%AE%E9%A2%98

**Comment by cytle** [comment]
嗯，收到，今天会更新下

**Comment by li914** [comment]
哈哈  谢谢大佬啊

**Comment by cytle** [comment]
已经更新

**Comment by qiaolevip** [comment]
速度，perfect，等下尝试一番。
