### ISSUE TITLE
控制台面板奇少，没有WXML

### ISSUE THREAD

**Issue by coppyC** [cytle/wechat_web_devtools#153]
![image](https://user-images.githubusercontent.com/25004510/45472927-32b4ed80-b768-11e8-9302-515553763a2d.png)
面板只有这几个选项，没有wxml，我换到1808300没有这个情况，
之前在码云clone，今天看到github有两个新版本，码云没有，就换了远程仓库，然后拉取
也就是拉取后出现的现象，回溯到前面的版本不会
就想问问大家有没有wxml的面板，还是只有我有问题。

**Comment by haohaoo** [comment]
今天我更新工具版本也出现了这个问题， 命令行报错信息为 "TypeError: Cannot read property 'src' of undefined",  source: (1)

未找到解决方案

**Comment by haohaoo** [comment]
在9月11日的更新里，这些 pannel 的创建和配置文件被删除了。

**Comment by cytle** [comment]
新版本改动挺大，这边需要看情况修改一些脚本了，手边没机器，晚上回去看下

**Comment by coppyC** [comment]
> 新版本改动挺大，这边需要看情况修改一些脚本了，手边没机器，晚上回去看下

辛苦了，目前用不到云开发，回滚到之前的版本，暂时够用，作者加油。

**Comment by haohaoo** [comment]
> > 新版本改动挺大，这边需要看情况修改一些脚本了，手边没机器，晚上回去看下
> 
> 辛苦了，目前用不到云开发，回滚到之前的版本，暂时够用，作者加油。

这个项目呢，还有个 storage.css 没删干净， 应该是作者操作失误 QAQ

**Comment by haohaoo** [comment]
> > 在9月11日的更新里，这些 pannel 的创建和配置文件被删除了。
> 
> 我看别人的不会（非linux平台），你指的9.11的更新配置文件被删除了是指这个项目还是官方工具。

这个项目呢，还有个 storage.css 没删干净， 应该是作者操作失误 QAQ

**Comment by cytle** [comment]
已经修复 https://github.com/cytle/wechat_web_devtools/pull/155
