### ISSUE TITLE
ubuntu 18.04 开发工具控制台缺少 wxml 及多项调试选项

### ISSUE THREAD

**Issue by haohaoo** [cytle/wechat_web_devtools#154]
您好

   我在 ubuntu 18.04 安装了该开发工具，按照文档流程完成安装，但是打开后控制台缺少了 wxml 等多项调试选项，尝试修改控制台 setting 和卸载删除文件夹后重新安装也无法使 wxml 调试选项出现。

如图所示，当点击 console 选项卡左边的小箭头会在命令行中出现报错 【 "TypeError: Cannot read property 'src' of undefined", source: (1) 】

![](http://or5v4cuf9.bkt.clouddn.com/18-9-13/91474332.jpg)

请问是不是我哪些弄错了或者需要添加一些修改？

**Comment by haohaoo** [comment]
回滚上一版本即可恢复，查看版本代码对比是 devtools 中这些 pannel 的创建文件被删除了

**Comment by cytle** [comment]
已经修复 https://github.com/cytle/wechat_web_devtools/pull/155
