### ISSUE TITLE
工具栏中到很多东西没了  

### ISSUE THREAD

**Issue by 316boss** [cytle/wechat_web_devtools#159]
![screenshot from 2018-09-17 20-09-48](https://user-images.githubusercontent.com/13294554/45622190-b860d200-bab5-11e8-97ce-6d9af23ccbfb.png)

这是我的工具截图，之前是有 wxml 之类的东西的，更新了一次后突然发现没了，这是什么情况，找了半天页没找到在哪里有选项打开

重新安装也没用

**Comment by cytle** [comment]
这个已经修复了,再更新下,就好了
