### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by lvchangqi** [cytle/wechat_web_devtools#16]
出现登录界面二维码,但是扫描确认之后无法登录,控制台打印出error
![image](https://user-images.githubusercontent.com/15379292/27950322-7302899a-6333-11e7-954e-8e205b0c6d01.png)

**Comment by cytle** [comment]
测试没有出现这样的问题。能提供更多信息吗？？

**Comment by lvchangqi** [comment]
不好意思 现在才来回复... 我电脑的问题 上次autoremove的时候系统给删掉了wine的一个依赖导致的, 我重新装了一下wine就解决了

**Comment by cytle** [comment]
哈哈，好的，issue关闭
