### ISSUE TITLE
请求一个被微信屏蔽的域名，客户端没进行验证

### ISSUE THREAD

**Issue by mrh111** [cytle/wechat_web_devtools#161]
就是一个被微信封了的域名，在工具里面请求 还是能正常访问呢，没有拦截  是工具的问题么

**Comment by haohaoo** [comment]
工具你勾选了 【不校验合法域名、web-view（业务域名）、TLS 版本以及 HTTPS 证书】 吧。
而且工具能不能用应该没有太大的意义吧。
