### ISSUE TITLE
我大概一个月之前下载的版本打开没问题的,目前新下载了一次,打开后,预览页面为空,提示重启死循环...请问怎么解决

### ISSUE THREAD

**Issue by a807966224** [cytle/wechat_web_devtools#167]

**Comment by a807966224** [comment]
各位,如果下载wechat_web_devtools-1.02.1809111.tar.gz这个版本,在wine-3.0.2 (Debian 3.0.2-3)环境下,启动会出现小程序左侧页面为空,真机预览正常的现象；我的解决方式是降级到wechat_web_devtools-1.02.1807200.tar.gz这个版本,安装后可正常运行.

**Comment by derekhe** [comment]
same issue

**Comment by duxingxia081** [comment]
我deepin系统，也是这样

**Comment by a807966224** [comment]
多启动几次 就好了   但是最终真的不是狠建议在linux上玩windows的工具




------------------ 原始邮件 ------------------
发件人: "duxingxia081"<notifications@github.com>; 
发送时间: 2019年10月17日(星期四) 下午4:48
收件人: "cytle/wechat_web_devtools"<wechat_web_devtools@noreply.github.com>; 
抄送: "算了吧"<807966224@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [cytle/wechat_web_devtools] 我大概一个月之前下载的版本打开没问题的,目前新下载了一次,打开后,预览页面为空,提示重启死循环...请问怎么解决 (#167)




我deepin系统，也是这样
