### ISSUE TITLE
sudo apt-get install wine-binfmt  安装的另一个方法

### ISSUE THREAD

**Issue by jeccyyeah** [cytle/wechat_web_devtools#169]
linux :ubuntu 16.04 
wine --version: 3.03( 按照步骤安装的默认版本）
执行“sudo apt-get install wine-binfmt” 
提示“package "wine-binfmt" has no installation candidate
度娘以下方法均失败：
方法1、apt-get update/apt-get upgrade；
方法2、增加/usr/share/binfmts/wine文件；
方法3、wine /path/to/wechat_web_devtools/package.nw/js/vendor/wcc.exe（需要替换为实际安装路径）安装依赖包 后仍无解

执行”sudo apt install binfms-support"后正常执行update-binfms命令后正常。大神来解释一下...

**Comment by jeccyyeah** [comment]
以上四个方法按顺序试一下...

**Comment by redchenjs** [comment]
最后那个安装命令是binfmt-support，楼主可能笔误@liuweiming1997

**Comment by vimiPonyai** [comment]
谢谢@redchenjs
