### ISSUE TITLE
gulp类似的前端工具生成小程序源码不更新

### ISSUE THREAD

**Issue by yolo2013** [cytle/wechat_web_devtools#17]
并不完美，实测如果使用了gulp类似的前端工具生成小程序源码， 开发者工具中无论如何都不会更新

**Comment by yolo2013** [comment]
还有一个问题是切换用户的时候，二维码出现不了，必须注销系统以后才能显示，希望关注。我也试着看看源码找到问题。

**Comment by cytle** [comment]
一直在用webpack生成代码，工具是会自动更新的。
1. 确认下有没有钩上: 设置->编辑器->编辑->`文件保存时自动编译小程序`
2. 能不能发一个小的demo给我

登录二维码的问题可能是加载时间有点久，我试了试没有问题。

**Comment by yolo2013** [comment]
是我操作有误了，第二个我这里确实非常慢。平时习惯了Mac上很快二维码出来。
