### ISSUE TITLE
编译时无法找到index.wxml

### ISSUE THREAD

**Issue by CNSH-Leo** [cytle/wechat_web_devtools#179]
BUG-1：

代码：云开发QuickStart / 普通开发QuickStart（TS）

运行环境：开发工具 v1.02.1811150

bug描述：运行编译时，console输出 ”./pages/index/index.wxml not found“

![screenshot from 2018-11-20 15-56-56](https://user-images.githubusercontent.com/19681028/48764608-18a90580-eceb-11e8-94e9-120968cb774f.png)

另外我在官方社区也发了[这个问题](https://developers.weixin.qq.com/community/develop/doc/0000a0945ccc200411b7f02135bc00?jumpto=comment&commentid=00060a588302986512b77252c56c)，有人建议我安装旧版本试试。。

所以另一个问题是，遇到新版有某些异常时如何安装旧版本的官方工具@。@
使用update工具似乎只能把软件升级到最新版，建议在README里面增加一个回滚版本的标准操作

**Comment by mojiajuzi** [comment]
@CNSH-Leo 我也遇到相同的问题，直接回滚到某一个特定的提交就好了

**Comment by CNSH-Leo** [comment]
尝试回滚到1025，解决了现在遇到的问题，希望尽快能用上新版本吧 T.T
