### ISSUE TITLE
2017.07.20 (0.20.191900) is out. 

### ISSUE THREAD

**Issue by m31271n** [cytle/wechat_web_devtools#18]
Time to update.

BTW:
> It's awesome to provide the way about update `package.nw`. Then contributors can help you maintaining this repo. What do you think ?

**Comment by cytle** [comment]
Here's a way to upgrade it. Can be used in the case of this project is not updated, may be accompanied by some bug.

1. The execution script will automatically download and install the latest developer tools which from Tencent

```shell
./bin/replace_package_nw.sh
```

2. During installation, confirm that the installation is in the `$HOME/.wine/drive_c/Program Files (x86)/Tencent/微信web开发者工具`

3. When finally done, remove the option to open the developer tool

Then execute ./bin/wxdt, if there is no question welcome to mention PR ~

**Finally,It's nice, I need contributors!! Are you interested in joining??**

😆😆😆

**Comment by m31271n** [comment]
Maybe we can migrate to https://github.com/BruceZhang1993/wechat_web_devtools  which is better. And  contribute to it. Just a suggestion. ;]
