### ISSUE TITLE
如何在Linux中使用命令行调用

### ISSUE THREAD

**Issue by ianjiang** [cytle/wechat_web_devtools#183]
# 问题：如何在Centos中使用命令行启动，登录，上传，预览

- 环境： Centos7
- 启动IDE命令
```bash
$ cd /root/git/wechat_web_devtools-master/dist
./nw
```
- 查看[微信开发者文档-命令行调用](https://developers.weixin.qq.com/miniprogram/dev/devtools/cli.html) 使用以下命令
```
$ cd /root/git/wechat_web_devtools-master/dist
./nw  -l --login-qr-output terminal
```
结果并未在命令行中显示二维码
![image](https://user-images.githubusercontent.com/1629800/49267466-a75d1580-f495-11e8-94ca-75d4eec29b8b.png)

- 在Mac中测试, 在iTerm2中输入命令
```
/Applications/wechatwebdevtools.app/Contents/Resources/app.nw/bin
$  bin ./cli -l --login-qr-output terminal
```
![image](https://user-images.githubusercontent.com/1629800/49267547-0a4eac80-f496-11e8-88c8-fe1dda287fdf.png)

**Comment by ShiningDan** [comment]
请教一下，如何在 CentOS 中安装 Wine 的，我这边没有成功，命令能分享一下吗

**Comment by ianjiang** [comment]
> 请教一下，如何在 CentOS 中安装 Wine 的，我这边没有成功，命令能分享一下吗

不好意思才看到，我是参考这个链接来使用的：https://www.systutorials.com/239913/install-32-bit-wine-1-8-centos-7/

**Comment by ianjiang** [comment]
经过半个月的折腾，终于在Centos上把开发者工具集成到Jenkins上了，如果有遇到同样问题的同学，可以来交流。以下是我的一些零碎的笔记和参考的文档:

# 安装环境
- Centos7
- Centos 图形界面
- VNC
- Centos安装微信开发者工具
- 打包编译小程序(wepy)

# Wechat IDE command
- 如何启动Ide？
```
/root/git/wechat_web_devtools-master/dist
./nw
```
- 查看安装路径
```
$ /root/git/wechat_web_devtools-master/bin
vi install_desktop.sh

cp "$root_dir/dist/wechat_dev_tools.desktop" $HOME/.local/share/applications/

$ cd ~/.local/share/applications
$ vi wechat_dev_tools.desktop

Exec=/root/git/wechat_web_devtools-master/bin/wxdt
```
- cli目录
```
/root/git/wechat_web_devtools-master/package.nw/js/common/cli

-rwxrwxrwx 1 root root    54 11\u6708 18 20:36 climac
-rwxrwxrwx 1 root root    96 11\u6708 18 20:36 cliwin.bat
-rw-r--r-- 1 root root   804 11\u6708 18 20:36 cli.win.js
-rw-r--r-- 1 root root 13955 11\u6708 18 20:36 index.js

```

- Chrome debug nodejs

    - 在Chrome中输入`chrome://inspect`
    - 输入命令: `node --inspect-brk file.js`


## 执行命令
- package url: `/root/git/wechat_web_devtools-master/package.nw`
- 执行目录: `/root/git/wechat_web_devtools-master/package.nw/js/common/cli`
- 调用ide的命令
```
$ cd /root/.local/share/applications

# 实际执行 wxdt文件
$ ls wechat_dev_tools.desktop
```

```
$ cd /root/git/wechat_web_devtools-master/bin

# 实际执行: /root/git/wechat_web_devtools-master/package.nw/js/common/cli/index.js
$ ls wxdt
```

`node.exe`, `wechat_dev_tools.desktop`在下面的目录:
```
/root/git/wechat_web_devtools-master/dist
```

## 命令变量
- global.appPath: `/root/git/wechat_web_devtools-master/bin/wechatwebdevtools`

- 查找ide启动web端口
```
[root@cd-dev bin]# netstat -apn | grep exe | grep tcp |grep  127.0.0.1
tcp        0      0 127.0.0.1:49910         0.0.0.0:*               LISTEN      15173/exe           
tcp        0      0 127.0.0.1:10944         0.0.0.0:*               LISTEN      15173/exe           
tcp        0      0 127.0.0.1:29792         0.0.0.0:*               LISTEN      15173/exe 
```
- 如何找到linux下ide的端口文件

```bash
[root@cd-dev ~]# find . -name '.ide'
./.config/微信开发者工具/Default/.ide
./AppData/Local/微信开发者工具/User data/Default/.ide
./AppData/Local/.ide
```
经测试`linux`下的ide端口文件在`/root/AppData/.config/微信开发者工具/Default/.ide`

- 成功使用命令将ide启动

![image](http://note.youdao.com/yws/res/5308/D0BDFD3800AE4A19A06A66BBEE12488D)

## 打包编译成功
```bash
$ npm run build:test0
[18:08:41] [写入] WXSS: dist/app.wxss
```


# Wechat IDE http



# Links
- [CentOS 中 YUM 安装桌面环境](https://cnzhx.net/blog/centos-yum-install-desktop/)
- [centos7系列安装vnc服务并授权用户访问](http://blog.51cto.com/shaonian/2090283)
- [[SOLVED] VNC black screen](https://www.centos.org/forums/viewtopic.php?t=66886)
- [No application menu in VNC](https://centos.org/forums/viewtopic.php?t=65156)
- [编译错误](https://github.com/cytle/wechat_web_devtools/issues/56)
- [How to Install Wine 32-bit on CentOS 7](https://www.systutorials.com/239913/install-32-bit-wine-1-8-centos-7/)
- [小程序命令行调用](https://developers.weixin.qq.com/miniprogram/dev/devtools/cli.html)
- [小程序HTTP调用](https://developers.weixin.qq.com/miniprogram/dev/devtools/http.html)
- [微信小程序集成 Jenkins](https://juejin.im/post/5b8caec751882542f038189e)
- [Linux微信web开发者工具](https://github.com/cytle/wechat_web_devtools)
- [Centos install chrome](https://www.tecmint.com/install-google-chrome-on-redhat-centos-fedora-linux/)
- [Run Chrome in centos with root](https://www.itzgeek.com/how-tos/linux/centos-how-tos/how-to-run-google-chrome-as-root-fedora-16-centos-6-rhel-6.html)
- [Debugging Node.js with Chrome DevTools](https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27)

**Comment by sept08** [comment]
你后面这个打印的二维码，是在Linux下成功用cli打印出来的么？有没有尝试http调用

**Comment by cytle** [comment]
新版本支持`cli`调用，更新后执行`./bin/cli`使用命令

https://github.com/cytle/wechat_web_devtools#%E5%91%BD%E4%BB%A4%E8%A1%8C%E8%B0%83%E7%94%A8

**Comment by sept08** [comment]
我换成了centos7，安装全过程没有问题，但在执行的时候命令行报 no protocol specified，执行启动命令行 .config/wechat_web_devtools/下并没有Default文件夹

**Comment by sept08** [comment]
没问题了，`no protocol specified` 这个报错是因为，非root用户的图形界面会被阻塞
