### ISSUE TITLE
求助！Centos安装wine-binfmt问题

### ISSUE THREAD

**Issue by royIdoodle** [cytle/wechat_web_devtools#185]
我利用`yum`安装了`wine`版本是`3.0.2`。
但是在安装`wine-binfmt`时，通过`yum`找不到安装包。在[pkgs.org](https://rosa.pkgs.org/2016.1/rosa-main-updates-i586/wine-binfmt-3.18-1-rosa2016.1.i586.rpm.html)上找到了安装包，但是需要`wine< 2:2.21-2`。所以，wine-binfmt安装不了。

我的问题是，一定要安装`wine-binfmt`是吗？如果是一定的话，CentOS的朋友们都如何解决安装问题的？

**Comment by jilieryuyi** [comment]
https://github.com/cytle/wechat_web_devtools/issues/158 用这个ok的，我就是用的这个

**Comment by royIdoodle** [comment]
> #158 用这个ok的，我就是用的这个

您好！谢谢你的帮助。但是，`wine`的安装其实是没有问题的。问题在于`wine-binfmt`的安装。请问你的`wine-binfmt`是如何安装的

**Comment by jilieryuyi** [comment]
我没安装wine-binfmt，直接使用了，一切ok

**Comment by royIdoodle** [comment]
> 我没安装wine-binfmt，直接使用了，一切ok

执行
```
./bin/wxdt
```
提示
```
./nw: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory
```

**Comment by cytle** [comment]
@royIdoodle 应该是 nwjs 没有安装好，参考这里[nw报错失败](https://github.com/cytle/wechat_web_devtools#binwxdt-install-%E6%8A%A5%E9%94%99%E5%A4%B1%E8%B4%A5)再试下
