### ISSUE TITLE
可以在ubuntu黑屏幕上打开吗

### ISSUE THREAD

**Issue by PerryYuan** [cytle/wechat_web_devtools#194]
可以在ubuntu黑屏幕上打开吗？就是ubuntu server打开可以吗？？不需要开发这些东西，只需要上传，然后用http命令这些上传代码。请问可以吗？

**Comment by JayCJP** [comment]
不支持吧……

**Comment by PerryYuan** [comment]
> 不支持吧……

恩，应该是了，谢谢回答哈。
