### ISSUE TITLE
与https://github.com/yuan1994/wechat_web_devtools的区别是什么？

### ISSUE THREAD

**Issue by hatelove85911** [cytle/wechat_web_devtools#20]
请问一下这个项目与
https://github.com/yuan1994/wechat_web_devtools
的区别是什么， 感觉你这个这个更好用一点， download下来就能用。 那个跑起来n多问题， 就是跑不起来。

**Comment by cytle** [comment]
都是一个东西，刚开始也看到了[yuan1994/wechat_web_devtools](https://github.com/yuan1994/wechat_web_devtools),但是太久没有更新，有很多问题，就用自己喜欢的姿势搞了现在这个项目。现在这个项目的有下面几个好的改动

1. 保持最新版本
2. 解决微信开发者工具在linux下的问题
  - 源码require文件大小写
  - 绑定快捷键问题
  - certificateDetailsPromise问题
  - 打开上面工具栏
3. 做了一个桌面图标
