### ISSUE TITLE
需要安装微信开发者工具么

### ISSUE THREAD

**Issue by sept08** [cytle/wechat_web_devtools#204]
尝试在命令行启动微信开发者工具，提示如下报错。想问下我是需要从微信官网下载开发者工具么
$ ./bin/cli -o
Initializing...
Please ensure that the IDE has been properly installed
init error:  { Error: ENOENT: no such file or directory, open '/data/users/tianjiaqi/.config/wechat_web_devtools/Default/.cli'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1291:33)
    at /data/users/tianjiaqi/tmp/wxchat-devtool/package.nw/js/common/cli/index.js:580:17
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/data/users/tianjiaqi/.config/wechat_web_devtools/Default/.cli' }

**Comment by cytle** [comment]
换了名字，可能是还没生成`.config/wechat_web_devtools`。先执行`./bin/wxdt` 直接打开ide，然后再用cli

**Comment by sept08** [comment]
[~/.config/wechat_web_devtools] 路径下没有开发者工具相关文件，只有`WeappVendor`文件夹
$ ll
total 4
drwxr-xr-x 3 tianjiaqi yzusers 4096 Feb 19 15:41 WeappVendor

执行`./bin/wxdt`有如下报错
./nw: error while loading shared libraries: libpangocairo-1.0.so.0: cannot open shared object file: No such file or directory

我以为是没有这个包`libpangocairo-1.0.so.0`，然后通过`yum`安装后，再次执行，依然包上述错误

**Comment by cytle** [comment]
第一次用吗，是不是nwjs没装好，参考下面文档
https://github.com/cytle/wechat_web_devtools#binwxdt-install-%E6%8A%A5%E9%94%99%E5%A4%B1%E8%B4%A5

**Comment by sept08** [comment]
这个readme我反复看过了，nwjs安装都正常，我遇到的这个问题应该是缺少相关依赖包

**Comment by jimmyrogue** [comment]
跟楼主一样的情况，我使用ssh连接服务器安装的，
```./bin/wxdt 提示 Gtk-WARNING **: 17:51:38.977: cannot open display:```
所以试试 ./bin/cli -l 
提示
```
Initializing...
Please ensure that the IDE has been properly installed
init error:  { Error: ENOENT: no such file or directory, open '/root/.config/wechat_web_devtools/Default/.cli'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1291:33)
    at /data/wechat_web_devtools/package.nw/js/common/cli/index.js:1:11342
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/root/.config/wechat_web_devtools/Default/.cli' }
```

**Comment by cytle** [comment]
@jimmyrogue 服务器有`GUI`环境吗，如果没有应该没安装好。更新了下readme的[命令行和HTTP调用](https://github.com/cytle/wechat_web_devtools#%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%92%8Chttp%E8%B0%83%E7%94%A8)，排查下是哪步出了问题

**Comment by jimmyrogue** [comment]
> @jimmyrogue 服务器有`GUI`环境吗，如果没有应该没安装好。更新了下readme的[命令行和HTTP调用](https://github.com/cytle/wechat_web_devtools#%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%92%8Chttp%E8%B0%83%E7%94%A8)，排查下是哪步出了问题

好的，我明天更新一下看看 ，感谢。

**Comment by dwightNgan** [comment]
> 跟楼主一样的情况，我使用ssh连接服务器安装的，
> `./bin/wxdt 提示 Gtk-WARNING **: 17:51:38.977: cannot open display:`
> 所以试试 ./bin/cli -l
> 提示
> 
> ```
> Initializing...
> Please ensure that the IDE has been properly installed
> init error:  { Error: ENOENT: no such file or directory, open '/root/.config/wechat_web_devtools/Default/.cli'
>     at Object.fs.openSync (fs.js:646:18)
>     at Object.fs.writeFileSync (fs.js:1291:33)
>     at /data/wechat_web_devtools/package.nw/js/common/cli/index.js:1:11342
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)
>     at Function.Module.runMain (module.js:686:11)
>     at startup (bootstrap_node.js:187:16)
>     at bootstrap_node.js:608:3
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'open',
>   path: '/root/.config/wechat_web_devtools/Default/.cli' }
> ```
> 
> 执行./bin/wxdt install的时候，到"生成/root/.config/wechat_web_devtools"的时候提示 ”标"/root/.config/wechat_web_devtools/WeappVendor/" 不是目录“，于是我自己去创建了这个目录。之后就提示安装成功了。
> 
> ![image](https://user-images.githubusercontent.com/6006189/53559294-c8accb00-3b84-11e9-8db4-eba76756a0fb.png)
> 
> 感觉就是这里出了问题，nwjs并没有安装，但是不知道怎么办了 @cytle

@jimmyrogue 你好我也遇到了这个问题，请问一下你是怎么解决的？
