### ISSUE TITLE
WeappVendor/wcc.exe: 这是什么错误

### ISSUE THREAD

**Issue by carvendy** [cytle/wechat_web_devtools#208]
我现在用是ubuntu ，wepy编译没有问题。到开发工具加载就有问题了。

/home/carvendy/.config/wechat_web_devtools/WeappVendor/wcc.exe: 1: /home/carvendy/.config/wechat_web_devtools/WeappVendor/wcc.exe: MZ����@���: not found
/home/carvendy/.config/wechat_web_devtools/WeappVendor/wcc.exe: 2: /home/carvendy/.config/wechat_web_devtools/WeappVendor/wcc.exe: Syntax error: "(" unexpected

**Comment by cytle** [comment]
重新执行下 `./bin/wxdt install`

**Comment by yangyangzuo** [comment]
dont' work
