### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by hatelove85911** [cytle/wechat_web_devtools#21]
刚想在ubuntu16.04上跑我的程序，但是遇到这个问题， 尝试了./bin/wxdt unisntall ./bin/wxdt install, 但是没用。 
还试过， rm /opt/tecent, ~/.config/微信web 开发工具， ~/.cache/微信web开发者工具/, 还是没用。

![image](https://user-images.githubusercontent.com/2359121/29260523-f5f6421a-80fc-11e7-8ec0-b83a0b086d7d.png)
![image](https://user-images.githubusercontent.com/2359121/29260534-0b894096-80fd-11e7-93d6-e4805a857f7d.png)

**Comment by cytle** [comment]
开启es6转es5试试

**Comment by hatelove85911** [comment]
一样， 刚开始是开启了的， 因为有错误就试着关掉了，但是还是一样。

**Comment by cytle** [comment]
要不试下clone[jectychen/wechat-v2ex](https://github.com/jectychen/wechat-v2ex)这个项目跑下
