### ISSUE TITLE
ubuntu command: kill

### ISSUE THREAD

**Issue by yz-xlame** [cytle/wechat_web_devtools#215]
------------------------------------------------------------------
生成/home/bum/.config/wechat_web_devtools
------------------------------------------------------------------
please wait 5s!
./nw: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
1s
2s
3s
4s
5s
kill nw
/home/bum/code/wechat_web_devtools/bin/replace_weapp_vendor.sh: line 48: kill: (4475) - No such process
 失败  command: kill
  at /home/bum/code/wechat_web_devtools/bin/replace_weapp_vendor.sh:1
  at 生成/home/bum/.config/wechat_web_devtools

**Comment by anyexinglu** [comment]
@yz-xlame 请问这个问题解决了么，我遇到了同样的问题
![image](https://user-images.githubusercontent.com/8243326/108475156-4cf53d00-72cb-11eb-8437-b62ec3cd9835.png)
