### ISSUE TITLE
安装成功，执行cli命令报错

### ISSUE THREAD

**Issue by DarkoPeng** [cytle/wechat_web_devtools#216]
环境：Ubuntu，16.04
执行 ./bin/wxdt install 成功
执行 ./bin/wxdt 成功
已经安装wine，which wine -> /usr/bin/wine

执行 ./bin/cli 报错：
```
Initializing...
Please ensure that the IDE has been properly installed
init error:  { Error: ENOENT: no such file or directory, open '/home/darko/.config/wechat_web_devtools/Default/.cli'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1291:33)
    at /home/darko/wechat_web_devtools/package.nw/js/common/cli/index.js:1:11342
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/darko/.config/wechat_web_devtools/Default/.cli' }
^C
```
备注，ubuntu16.04 安装 wine-binfmt 失败，提示找不到这个包？按照这篇博客( https://blog.izgq.net/archives/1008/ )的办法新建了一个`/usr/share/binfmts/wine`文件，完成了安装过程。

需求：是打算在Linux服务器上和jekins集成做为打包上传的工具的，有类似需求的朋友吗？有没有成功的经验介绍下，能在linux服务器上用命令行预览上传代码吗？

**Comment by cytle** [comment]
@DarkoPeng IDE可以运行，应该不会有这错误

**Comment by DarkoPeng** [comment]
> @DarkoPeng IDE可以运行，应该不会有这错误

我是通过ssh连接到服务器上试的，没有图形界面也不知道ide有没有跑起来，安装的过程没有报错，如果没有ide启动，不能直接用命令行模式使用吗？

**Comment by cytle** [comment]
> > @DarkoPeng IDE可以运行，应该不会有这错误
> 
> 我是通过ssh连接到服务器上试的，没有图形界面也不知道ide有没有跑起来，安装的过程没有报错，如果没有ide启动，不能直接用命令行模式使用吗？

是的，不能，必须有图形界面，可以查看readme中的说明
