### ISSUE TITLE
在docker里运行 update-binfmts会报错

### ISSUE THREAD

**Issue by tanzhihang** [cytle/wechat_web_devtools#220]
`
mount: /proc/sys/fs/binfmt_misc: permission denied.
update-binfmts: warning: Couldn't mount the binfmt_misc filesystem on /proc/sys/fs/binfmt_misc.
`
原因是在docker里 /proc/sys/fs/binfmt_misc是只读，请问怎样解决

**Comment by cytle** [comment]
我之前查了下，无法解决，我现在是不通过binfmt来使用wine  [Dockerfile#L41-L47](https://github.com/cytle/wechat_web_devtools/blob/master/Dockerfile#L41-L47)

**Comment by cytle** [comment]
然后在容器内执行 [Dockerfile#L53-L54](https://github.com/cytle/wechat_web_devtools/blob/master/Dockerfile#L53-L54)wine 配置

**Comment by cytle** [comment]
如果不在docker里跑ide，只为调cli的话，不用安装wine也可以

**Comment by tanzhihang** [comment]
@cytle 对，我只是为了用cli。不是要启动微信开发中工具才能调用cli吗？

**Comment by cytle** [comment]
是需要启动开发者工具，不过这不依赖wine，wine是之后预览小程序时编译用到的。cli里面调的都不依赖wine

**Comment by tanzhihang** [comment]
@cytle 意思是开发者工具的ui其实是nwjs做的，不需要wine是吧？

**Comment by cytle** [comment]
嗯，是的
