### ISSUE TITLE
窗口无法调整大小。。KDE 和 Budgie 桌面一样问题

### ISSUE THREAD

**Issue by razonyang** [cytle/wechat_web_devtools#221]
系统：Arch Linux

只有最小化和关闭按钮。。

注：注销微信后，再登录一次貌似又可以，不过这个问题经常出现，不确保下次重新登录会解决。

![{W91O4_`NF~5K69~NS0I11Y](https://user-images.githubusercontent.com/17720932/54262372-f8a69600-45a8-11e9-8df4-aabd409581aa.png)

**Comment by zhaisasi** [comment]
同样问题，求解？

**Comment by Jon-000** [comment]
我也是这个问题,ubuntu 18.04

**Comment by chunfantasy** [comment]
Workaround: `win + ⬆️`

**Comment by razonyang** [comment]
> Workaround: `win + ⬆️`

Not working.

**Comment by mmqic** [comment]
同ubuntu 18.04. T T
