### ISSUE TITLE
导入小程序死机？

### ISSUE THREAD

**Issue by lenLch** [cytle/wechat_web_devtools#226]
在工具里面打入小程序，选择文件的时候，就一直卡在那，什么也做不了？

**Comment by izhangzhen** [comment]
我也是这个问题，导入小程序选择文件会卡死

**Comment by fanfpy** [comment]
我也是的呢 deepin15.9

**Comment by shiqingk** [comment]
deepin 15.9 +1

**Comment by liyiheng1111** [comment]
我也是 deepin。。。

**Comment by liyiheng1111** [comment]
可以通过新建项目选择该项目，然后切到导入页来临时解决

**Comment by beyondalbert** [comment]
这个啥时候可以修好呢？

**Comment by dollarkillerx** [comment]
ubuntu18.04也有这个问题 导入卡死

**Comment by izhangzhen** [comment]
目前有个解决办法，在新建项目那里选择现有的小程序目录，不要点新建，再点到那个导入项目的tab，这时候默认是刚才选的项目，只需要填入appid 导入就行了




在2019年03月27日 14:38，Dollarkillerx 写道：

ubuntu18.04也有这个问题 导入卡死

**Comment by lenLch** [comment]
> 目前有个解决办法，在新建项目那里选择现有的小程序目录，不要点新建，再点到那个导入项目的tab，这时候默认是刚才选的项目，只需要填入appid 导入就行了 在2019年03月27日 14:38，Dollarkillerx 写道： ubuntu18.04也有这个问题 导入卡死 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
 

@我都是用默认的名字，将项目名改成他的默认名

**Comment by zhanbai** [comment]
导入卡死 +1

**Comment by lenLch** [comment]
能不能早点解决这个问题呀？ 使用框架打包的dist文件夹，通过默认名的小伎俩不好使呀/(ㄒoㄒ)/~~

**Comment by chenxf0619** [comment]
import的时候卡死在 select folder

**Comment by cytle** [comment]
重复 https://github.com/cytle/wechat_web_devtools/issues/207
