### ISSUE TITLE
docker启动bug

### ISSUE THREAD

**Issue by einsqing** [cytle/wechat_web_devtools#227]
/wxdt/bin/docker-entrypoint.sh: 6: [: missing ]

**Comment by hbxks18** [comment]
一样的情况，作者大大帮忙看看下
/wxdt/bin/docker-entrypoint.sh: 6: [: missing ]

**Comment by cytle** [comment]
不好意思，这个问题修了，忘记重新构建image了，已经重新推到docker hub了。

文档： https://github.com/cytle/wechat_web_devtools#docker
