### ISSUE TITLE
移动设备的inspect调试功能无法使用

### ISSUE THREAD

**Issue by ihipop** [cytle/wechat_web_devtools#23]
![_ _20170822141540](https://user-images.githubusercontent.com/423077/29552518-53d19012-874a-11e7-909a-a7f1539c8ac3.png)
出来是个空白框。
同机器的chrome是可以用的。
已经排除了是本机chrome的影响

![image](https://user-images.githubusercontent.com/423077/29552654-c9b22e0e-874a-11e7-8c3d-3f41974d179f.png)

**Comment by cytle** [comment]
这问题不会修复
