### ISSUE TITLE
cli --upload dev@/project 上传项目报错 'Path must be a string. Received undefined\'

### ISSUE THREAD

**Issue by shynome** [cytle/wechat_web_devtools#231]
报错:
```
"{\"code\":40000,\"error\":\"Error TypeError: Path must be a string. Received undefined\"}"
```

官方说后续修
https://developers.weixin.qq.com/community/develop/doc/000ee24bb8c848067158cf5135b800

**Comment by linson2016** [comment]
#### 如果是使用docker,第一次运行该命令即可
`docker exec -it wxdt cli -p /projects/your-project`

**Comment by pbestz** [comment]
> 报错:
> 
> ```
> "{\"code\":40000,\"error\":\"Error TypeError: Path must be a string. Received undefined\"}"
> ```
> 
> 官方说后续修
> https://developers.weixin.qq.com/community/develop/doc/000ee24bb8c848067158cf5135b800

@shynome 现在解决了么？

**Comment by shynome** [comment]
开发者工具 2019.04.17 的版本解决了

**Comment by shynome** [comment]
希望能有 v1.02.1904091 的 tag ，这样镜像制作的时候比较方便 @cytle

**Comment by pbestz** [comment]
> 开发者工具 2019.04.17 的版本解决了

怎么操作？我用bin/update_package_nw.sh脚本更新不成功

**Comment by shynome** [comment]
你可以使用我的 docker 镜像看看，shynome/wechat_web_devtools ，刚刚和更新到和这个仓库一致的最新版本

**Comment by pbestz** [comment]
> 你可以使用我的 docker 镜像看看，shynome/wechat_web_devtools ，刚刚和更新到和这个仓库一致的最新版本

好的，我试试看下

**Comment by pbestz** [comment]
> 你可以使用我的 docker 镜像看看，shynome/wechat_web_devtools ，刚刚和更新到和这个仓库一致的最新版本

@shynome 求教下如何更新的？

**Comment by shynome** [comment]
下载了这个仓库对应 commit 的压缩包进行更新
