### ISSUE TITLE
执行升级后，真机调试无法启动

### ISSUE THREAD

**Issue by gangbanbro** [cytle/wechat_web_devtools#236]
升级成功（部分未成功），提示如下：
 成功  fix: 修改项目名字, 修复标题栏乱码问题
------------------------------------------------------------------
fix: 重新编译node-sync-ipc
------------------------------------------------------------------
/home/zzg/wechat_web_devtools/bin/fix_node_sync_ipc.sh:行11: npm: 未找到命令
/home/zzg/wechat_web_devtools/bin/fix_node_sync_ipc.sh:行14: npm: 未找到命令
 失败  command: bash
  at ./bin/update_package_nw.sh:1
  at fix: 重新编译node-sync-ipc

升级完成进去后，真机调试无法使用，报错。

当前版本为git最新版本。升级后版本为（1.02.1904090）

**Comment by gangbanbro** [comment]
确认了下是环境未安装npm。装好后继续更新，报错如下

 成功  fix: 重新编译node-sync-ipc
------------------------------------------------------------------
doc: 更新文档
------------------------------------------------------------------
sed：-e 表达式 #1，字符 52：“s”命令的RHS非法引用\1
 失败  command: sed
  at ./bin/update_package_nw.sh:1
  at doc: 更新文档


真机调试依然不可用
提示
TypeError: Cannot read property '0' of undefined

**Comment by gangbanbro** [comment]
应该是正则表达式匹配目录出错，当前环境为deepin

**Comment by gangbanbro** [comment]
不行。还原也没用。真机调试在deepin上没法用吗

提示
Error: node-sync-ipc is broken.

**Comment by cytle** [comment]
已经修复
