### ISSUE TITLE
update_package_nw.sh: line 19: http: command not found

### ISSUE THREAD

**Issue by justintung** [cytle/wechat_web_devtools#24]
执行 update_package_nw.sh
出现错误
`当前wechat_v: 0.21.201800  
./bin/update_package_nw.sh: line 19: http: command not found
`
http命令是什么？怎么安装的

**Comment by RonLiu36** [comment]
安装 httpie 工具
如果你是Ubuntu 环境 ,执行 sudo apt install httpie
