### ISSUE TITLE
升级到官方1.0版本

### ISSUE THREAD

**Issue by imLibo** [cytle/wechat_web_devtools#25]
大神，官方1.0版本发布了额，支持wsx语法，期待大神快快更新！真的是苦了ubuntu的小兄弟们了。

**Comment by cytle** [comment]
这几天研究下😆

**Comment by taoqf** [comment]
Debian可以么？Windows上真难用啊，慢地要死

**Comment by yolo2013** [comment]
关注下，似乎改动不小

**Comment by cytle** [comment]
移植了下package.nw,发现没有大问题，如下

![image](https://user-images.githubusercontent.com/5120505/29968567-da17867e-8ee1-11e7-8e45-2ac63398e665.png)

我看了下`mac`开发者工具nwjs版本升级了（还不确定是什么版本的），所以此处没有升级，没有大问题。小伙伴们观察下哈。

**升级步骤**: 代码在分支: **version_1**，切来后，直接`./bin/wxdt`

**Comment by imLibo** [comment]
好的，谢谢大神，大神辛苦了！

**Comment by cytle** [comment]
微信团队不会再维护老版本开发者工具了，现在把`master`切到新版开发者工具，并且升级到最新版。新版本没啥bug，因此关闭此issue
