### ISSUE TITLE
希望删除 package.nw 改为自行安装，并可以指定版本，package.nw 太大了

### ISSUE THREAD

**Issue by jiankafei** [cytle/wechat_web_devtools#269]
希望删除 package.nw 改为自行安装，并可以指定版本，package.nw 太大了

**Comment by jiankafei** [comment]
在 readme.md 里说明当前版本适配的微信小程序版本就行。

**Comment by cytle** [comment]
嗯，你这个想法我之前尝试过，限于个人精力没有继续下去。实际难度不大，不过到用户手中会出现各种问题，最后还是以此方式为主。

这个项目的tag和微信开发者工具的版本对应。readme的badge为微信开发者工具版本和对应的nwjs版本
