### ISSUE TITLE
1.0版本安装后，wxml解析错误

### ISSUE THREAD

**Issue by justintung** [cytle/wechat_web_devtools#28]
VM112:1 Sun Sep 03 2017 09:38:09 GMT+0800 (CST) wxml 文件，编译错误
VM112:2 undefined
undefined
(anonymous) @ VM112:2
VM114:1 Sun Sep 03 2017 09:38:09 GMT+0800 (CST) 渲染层错误
VM114:2 run-detectors: unable to find an interpreter for /home/justin/.config/微信web开发者工具/WeappVendor/wcc.exe

已执行wcc.exe重新编译

**Comment by Sweetmile** [comment]
所以是怎么做的呢？

**Comment by QQ876684433** [comment]
我只重新安装了一遍wine，然后就可以了
