### ISSUE TITLE
项目启动后能够通过预览编译但是模拟器无法显示内容

### ISSUE THREAD

**Issue by liudliu1992** [cytle/wechat_web_devtools#281]
# 错误提示
![图片](https://user-images.githubusercontent.com/21699187/68826420-d2596d00-06d8-11ea-88af-f0bc6e0c5693.png)

**Comment by liudliu1992** [comment]
![](file:///home/leo/Desktop/%E6%B7%B1%E5%BA%A6%E6%88%AA%E5%9B%BE_%E9%80%89%E6%8B%A9%E5%8C%BA%E5%9F%9F_20191114121800.png)

**Comment by qwertyuiop6** [comment]
我也是，可以预览但是模拟器没有内容显示
![image](https://user-images.githubusercontent.com/26669271/71519455-8b26e480-28f2-11ea-9e6e-569723f1ba81.png)

**Comment by shanjixiaboss** [comment]
> 我也是，可以预览但是模拟器没有内容显示
> ![image](https://user-images.githubusercontent.com/26669271/71519455-8b26e480-28f2-11ea-9e6e-569723f1ba81.png)

请问查到原因吗,解决了没?

**Comment by seast19** [comment]
我重新点编译后也是只显示顶级tab，等待一分钟这样后就正常显示了

**Comment by liudliu1992** [comment]
> 我重新点编译后也是只显示顶级tab，~等待一分钟这样后就正常显示了~其实是没安装wine，使用readme的第一种安装wine的方式安装后可正常使用
 谢谢，安装wine果然能显示了
