### ISSUE TITLE
upload更新后出现i is not defined报错

### ISSUE THREAD

**Issue by veeking** [cytle/wechat_web_devtools#298]
1、执行update更新后出现i is not defined报错
2、执行sed -bri -e 's/enableServicePort:!1/enableServicePort:!0/g' /wxdt/package.nw/core.wxvpkg后依然一直提示工具的服务端口已关闭

**Comment by dragonation** [comment]
enableServicePort新版本好像已经被移到wxvpkg文件里面去了，没有外部修改的方法。修改的数据则是存在了localstorage里面

**Comment by veeking** [comment]
> enableServicePort新版本好像已经被移到wxvpkg文件里面去了，没有外部修改的方法。修改的数据则是存在了localstorage里面

按照#225的方法，修改了wxvpkg文件里的enableServicePort设置，但是依然提示端口关闭中。你们是怎么开启服务端口的?

**Comment by dragonation** [comment]
那我估计是已经有配置存在localstorage里面了，所以你改默认值会无效

**Comment by dragonation** [comment]
我查了一下，估计是这个位置：
JSON.parse(localStorage.getItem("reduxPersist:settings")).security.enableServicePort

**Comment by veeking** [comment]
> JSON.parse(localStorage.getItem("reduxPersist:settings")).security.enableServicePort

你的端口是怎么开启的？

**Comment by zjsun** [comment]
> 1、执行update更新后出现i is not defined报错
> 2、执行sed -bri -e 's/enableServicePort:!1/enableServicePort:!0/g' /wxdt/package.nw/core.wxvpkg后依然一直提示工具的服务端口已关闭

1问题我已经提pr了，我的场景比较简单，我只需要cli upload正常使用

**Comment by dragonation** [comment]
> > 1、执行update更新后出现i is not defined报错
> > 2、执行sed -bri -e 's/enableServicePort:!1/enableServicePort:!0/g' /wxdt/package.nw/core.wxvpkg后依然一直提示工具的服务端口已关闭
> 
> 1问题我已经提pr了，我的场景比较简单，我只需要cli upload正常使用

我看了一下，跟我解决方案差不多，不过我用的是require("fs").join，用来避免不知道啥时候又出问题

**Comment by dragonation** [comment]
> > JSON.parse(localStorage.getItem("reduxPersist:settings")).security.enableServicePort
> 
> 你的端口是怎么开启的？

我自己是通过图形化界面开启的，另外在图形化界面的命令里有一个启动选项--enable-service-port可以通过命令行开启，但是貌似cli不支持这个选项
