### ISSUE TITLE
how to reinstall?

### ISSUE THREAD

**Issue by czjs2** [cytle/wechat_web_devtools#3]
please wait 5s!
4s
3s
2s
1s
after 5s
/home/admin/program/wechat_web_devtools/bin/replace_weapp_vendor.sh: 27: kill: No such process

Fail! Please reinstall

**Comment by cytle** [comment]
eh... Just try again

**Comment by czjs2** [comment]
我重新安装 ./bin/wxdt 
就输出了一行
/home/amdin/program/wechat_web_devtools
还是不运行，我想知道怎么样能把你的项目删除干净？

**Comment by cytle** [comment]
先`git pull`，更新到最新，接着直接执行`./dist/nw`试试

如果不行，删除`dist`文件夹，然后执行`./bin/wxdt`

**Comment by czjs2** [comment]
删除dist文件夹，然后执行./bin/wxdt 成功了！！ 
非常感谢！！ @cytle
