### ISSUE TITLE
这个uninstall后再install也不行啊

### ISSUE THREAD

**Issue by edboffical** [cytle/wechat_web_devtools#30]
/home/edb/.config/微信web开发者工具/WeappVendor/wcc.exe: 1: /home/edb/.config/微信web开发者工具/WeappVendor/wcc.exe: MZ����@���: not found
/home/edb/.config/微信web开发者工具/WeappVendor/wcc.exe: 2: /home/edb/.config/微信web开发者工具/WeappVendor/wcc.exe: �J�Y��1�8���: not found
/home/edb/.config/微信web开发者工具/WeappVendor/wcc.exe: 1: /home/edb/.config/微信web开发者工具/WeappVendor/wcc.exe: Syntax error: word unexpected (expecting ")")

**Comment by edboffical** [comment]
是开发者工具里的错误提示

**Comment by cytle** [comment]
uninstall完了，删除`/home/edb/.config/微信web开发者工具`,再安装试试

**Comment by edboffical** [comment]
uninstall完/home/edb/.config/微信web开发者工具 这个文件夹就已经没了 被删了

**Comment by edboffical** [comment]
[8763:8781:0906/180009:ERROR:simple_backend_impl.cc(134)] Failed to create directory: /home/edb/.cache/微信web开发者工具/Default/Cache
[8763:8781:0906/180009:ERROR:simple_backend_impl.cc(584)] Simple Cache Backend: wrong file structure on disk: /home/edb/.cache/微信web开发者工具/Default/Cache
[8763:8782:0906/180009:ERROR:cache_util.cc(134)] Unable to move cache folder /home/edb/.cache/微信web开发者工具/Default/Cache to /home/edb/.cache/微信web开发者工具/Default/old_Cache_000
[8763:8782:0906/180009:ERROR:cache_creator.cc(134)] Unable to create cache

**Comment by lvchangqi** [comment]
把缓存也删了 重新建立wine的win32运行环境

**Comment by cytle** [comment]
还是不可以吗？

**Comment by edboffical** [comment]
不可以 @lvchangqi 缓存在哪里？

**Comment by cytle** [comment]
`/home/edb/.cache/微信web开发者工具`

**Comment by edboffical** [comment]
删了清了 重新clone分支 安装 还是不行 不知道咋回事 就我一个人又这个问题吗

**Comment by cytle** [comment]
安装时sudo权限？

现在报什么错误？

**Comment by edboffical** [comment]
一样的问题 sudo更不行了

**Comment by cytle** [comment]
这问题
```
[8763:8781:0906/180009:ERROR:simple_backend_impl.cc(134)] Failed to create directory: /home/edb/.cache/微信web开发者工具/Default/Cache
```
还是

```
/home/edb/.config/微信web开发者工具/WeappVendor/wcc.exe: 1: /home/edb/.config/微信web开发者工具/WeappVendor/wcc.exe: MZ������@������: not found
```

**Comment by edboffical** [comment]
是not found

**Comment by cytle** [comment]
把 `wechat_web_devtools/bin/WeappVendor`覆盖`.config/微信web开发者工具/WeappVendor`

**Comment by edboffical** [comment]
重新clone了一下出现安装微信开发者工具对应nwjs版本：0.19.4
cp: 无法获取'/tmp/wxdt_xsp/nwjs-sdk-v0.19.4-linux-x64/*' 的文件状态(stat): 权限不够
update nwjs success
./bin/wxdt: 行 22: ./nw: 没有那个文件或目录

nw没有那个文件或目录是什么鬼

**Comment by cytle** [comment]
可能之前sudo, 删除/tmp/wxdt_xsp ，然后正常权限再来一次

**Comment by edboffical** [comment]
可以了 麻烦了 感谢

**Comment by cytle** [comment]
不用客气，最终问题是没有安装好吗？有没有啥建议？

**Comment by gooqiao** [comment]
@edboffical 怎么解决的啊楼主？我现在跟你一样的错误：

/home/ming/.config/微信web开发者工具/WeappVendor/wcc.exe: 1: /home/ming/.config/微信web开发者工具/WeappVendor/wcc.exe: MZ����@���: not found
/home/ming/.config/微信web开发者工具/WeappVendor/wcc.exe: 2: /home/ming/.config/微信web开发者工具/WeappVendor/wcc.exe: cannot open .text�.data�0@�.rdata��@�*@@.bssP�: No such file
/home/ming/.config/微信web开发者工具/WeappVendor/wcc.exe: 2: /home/ming/.config/微信web开发者工具/WeappVendor/wcc.exe: �qZ�7�8�: not found
/home/ming/.config/微信web开发者工具/WeappVendor/wcc.exe: 3: /home/ming/.config/微信web开发者工具/WeappVendor/wcc.exe: Syntax error: word unexpected (expecting ")")

**Comment by gooqiao** [comment]
已解决，参考 https://github.com/cytle/wechat_web_devtools/issues/56#issuecomment-359259213
程序安装更低版本的wine而非winehq即可。
