### ISSUE TITLE
1.03.2005140版本不能使用update_package_nw.sh升级

### ISSUE THREAD

**Issue by pkfguo** [cytle/wechat_web_devtools#305]
package_nw的文件夹路径变更了,而且手动更新也无法使用cli调用

**Comment by biaji** [comment]
cp: 无法获取'/tmp/wxdt_xsp/wechat_web_devtools_1.03.2006090_x64/$APPDATA/Tencent/微信开发者工具/package.nw' 的文件状态(stat): 没有那个文件或目录

此目录已变为：

/tmp/wxdt_xsp/code/package.nw

------
```diff
diff --git a/bin/update_package_nw.sh b/bin/update_package_nw.sh
index 0d5069fe4..31ece0e5a 100755
--- a/bin/update_package_nw.sh
+++ b/bin/update_package_nw.sh
@@ -108,7 +108,7 @@ fi
 start_step '解压微信开发者工具'
 
 wcwd_file_target="$tmp_dir/wechat_web_devtools_${wechat_v}_x64"
-wcwd_file_package_nw_dir="\$APPDATA/Tencent/微信开发者工具/package.nw"
+wcwd_file_package_nw_dir="code/package.nw"
 
 7z x $wcwd_file -o$wcwd_file_target -y $wcwd_file_package_nw_dir
```

**Comment by pillarstone** [comment]
升级后，打开后，项目一直加载中

**Comment by dragonation** [comment]
> 升级后，打开后，项目一直加载中

npm的module有和系统与node版本冲突的native模块，重新npm install一下，gyp之后一般就好了

**Comment by pillarstone** [comment]
> > 升级后，打开后，项目一直加载中
> 
> npm的module有和系统与node版本冲突的native模块，重新npm install一下，gyp之后一般就好了

你好，我是小白。请问具体怎么操作

**Comment by youleji** [comment]
> > > 升级后，打开后，项目一直加载中
> > 
> > 
> > npm的module有和系统与node版本冲突的native模块，重新npm install一下，gyp之后一般就好了
> 
> 你好，我是小白。请问具体怎么操作

建议使用  https://github.com/dragonation/wechat-devtools

这个版本新。

**Comment by owen-gxz** [comment]
![image](https://user-images.githubusercontent.com/8510542/112711126-fbab1f80-8f00-11eb-8429-722ad8206484.png)
这东西是白色的怎么解决？

@dragonation

**Comment by CeliaSmile** [comment]
更新报错，请问这个要怎么解决
![image](https://user-images.githubusercontent.com/46587721/120263314-0baef900-c2ce-11eb-9a0d-19d94103cd6e.png)
