### ISSUE TITLE
使用的docker启动，并cli -p预览，提示版本太旧需要升级？

### ISSUE THREAD

**Issue by lidaomin** [cytle/wechat_web_devtools#307]
Initializing...
idePortFile: /root/.config/wechat_web_devtools/Default/.ide
IDE server has started, listening on http://127.0.0.1:47053
initialization finished
preparing preview...

StatusCodeError: 400 - "{\"code\":40000,\"error\":\"Error Error: The current version is too old, please upgrade the tool\"}"

这个怎么升级？有没有人遇到这个问题？

**Comment by dragonation** [comment]
cli有新版本了，你需要升级开发者工具。另外cli已经有官方纯node版本了，不需要再使用开发者工具了，你可以去npm上搜一下

**Comment by lidaomin** [comment]
> cli有新版本了，你需要升级开发者工具。另外cli已经有官方纯node版本了，不需要再使用开发者工具了，你可以去npm上搜一下

**Comment by lidaomin** [comment]
好的，谢谢，我研究下
