### ISSUE TITLE
Mac OSX 环境下，cli 无法自动调试小程序，报错： "Error: Port is not provided (Code 10)

### ISSUE THREAD

**Issue by yxdt** [cytle/wechat_web_devtools#309]
命令行如下：
(base) path % /Applications/wechatwebdevtools.app/contents/macos/cli auto --project /path/to/proj/ --port 9420 --debug

操作系统 Mac OSX 10.15.5
微信开发工具版本号：1.03.2006090 和1.03.2006091 都不行
已经按文档要求，开启了安全设置下的相应端口

开发工具会运行，但停留在了启动页面，不会打开要自动化的项目。
同样的配置，在windows10下是可以正常运行的。

错误输出如下：
[info] args {
  _: [ 'auto' ],
  project: '/path/to/proj/',
  port: 9420,
  debug: true,
  '$0': 'js/common/cli/index.js'
}
[info] installPath /Applications/wechatwebdevtools.app/Contents/MacOS
[info] userDirPath /Users/username/Library/Application Support/微信开发者工具/50a7d9210159a32f006158795f893857/Default
[info] appPath /Applications/wechatwebdevtools.app/Contents/MacOS/wechatwebdevtools
⠋ initialize
[info] updatePort cliport=3800
[info] IDE not started, proceed to start IDE. Status detection detail: 
 Error: connect ECONNREFUSED 127.0.0.1:9420
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9420
} 

[info] spawn app path /Applications/wechatwebdevtools.app/Contents/MacOS/wechatwebdevtools
[info] spawn args [
  '.',
  '--cli',
  '--remote-port',
  '3800',
  '',
  '',
  '',
  '--ide-http-port',
  '9420'
⠋ launch ide
[info] connect upgrade response 200

[info] ws connect 47342 94bd51e45e0da621a0e4476db96f02f9943179f0 5da90635c7cb30120b78ca447507e741
⠙ connect upgrade using port 47342[info] long connection established

✔ IDE server started successfully, listening on http://127.0.0.1:9420
✔ Using AppID: mywxappid
✖ Fetching AppID (mywxappid) detailed information
[error] {
  code: 10,
  message: 'Error: 错误 Error: Port is not provided (code 10)Error: Port is not provided\n' +
    '    at Object.exports.auto [as method] (/Applications/wechatwebdevtools.app/Contents/Resources/package.nw/core.wxvpkg/1d3c44fb45826718b091c4f56f6d9ab0.js:1:535)\n' +
    '    at Object.<anonymous> (/Applications/wechatwebdevtools.app/Contents/Resources/package.nw/core.wxvpkg/7a975443f52e91830ae1d65cdf8c86db.js:1:3590)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:85:5)'
}

**Comment by dragonation** [comment]
...这个不是linux项目吗……macOS有官方支持的吧？

**Comment by disburden** [comment]
乌龙了,楼主该不会不知道微信小程序开发工具官方就有提供mac版吧

**Comment by yxdt** [comment]
我在Windows 和Mac都在进行调试，Windows下成功的原因是port端口号可以设为固定值，所以调试器可以连接开发工具，而Mac下似乎没有办法固定端口号，调试器自然连不上。
