### ISSUE TITLE
1.0的版本，wx.request　成功后，没有回调success,fail,complete.

### ISSUE THREAD

**Issue by RonLiu36** [cytle/wechat_web_devtools#31]
1.0的版本，wx.request　成功后，没有回调success,fail,complete.
我把项目用1.0上传后，真机测试是可以成功回调的。
请问怎么解决这个问题。

**Comment by cytle** [comment]
![image](https://user-images.githubusercontent.com/5120505/30236489-e3b4d4ae-954c-11e7-9f28-386c2a7f412c.png)

开这个了吗

**Comment by cytle** [comment]
终端有没有显示什么错误

**Comment by RonLiu36** [comment]
没开不校验安全域名，我开启后尝试了是可以的，谢谢
我在老版本没开启也可以成功回调的，是不是新版IDE对这个有特殊设置。

**Comment by cytle** [comment]
不是安全域名肯定是不行的，老版也是不会回调的
