### ISSUE TITLE
Ubuntu20.04编译小程序的时候会报错，并无限弹出一大堆文件夹窗口

### ISSUE THREAD

**Issue by Black-Jacki** [cytle/wechat_web_devtools#318]
按照文档安装了wine，wine-binfmts以及其他相关的东西。打开也一切正常，就是导入dist之后，微信开发者工具里点编译就会报错并无限弹出一大堆文件夹窗口。希望能得到帮助，谢谢～
-------------------------------------------------------------------------------------------------------
是不是和deepin-wine有关系？因为装了个微信所以本机上装有deepin-wine2.18和wine6.0

**Comment by kyleliu-code** [comment]
https://blog.csdn.net/iamzhoujunjia/article/details/113826861  用这个 更新版的开发工具吧，我是 20.10 系统，运行起来了，感觉很棒棒

**Comment by Black-Jacki** [comment]
感谢！这个必须要用deepin-wine安装吗？wine6.0i可以否？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月14日(星期三) 晚上7:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cytle/wechat_web_devtools] Ubuntu20.04编译小程序的时候会报错，并无限弹出一大堆文件夹窗口 (#318)





 
https://blog.csdn.net/iamzhoujunjia/article/details/113826861  用这个 更新版的开发工具吧，我是 20.10 系统，运行起来了，感觉很棒棒

**Comment by Black-Jacki** [comment]
已用上，谢谢大佬。希望越来越好




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月14日(星期三) 晚上7:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cytle/wechat_web_devtools] Ubuntu20.04编译小程序的时候会报错，并无限弹出一大堆文件夹窗口 (#318)





 
https://blog.csdn.net/iamzhoujunjia/article/details/113826861  用这个 更新版的开发工具吧，我是 20.10 系统，运行起来了，感觉很棒棒
