### ISSUE TITLE
微信开发者工具v.01.170925版本编译有问题哦

### ISSUE THREAD

**Issue by jerryliu306** [cytle/wechat_web_devtools#37]
/home/jerry/.config/微信web开发者工具/WeappVendor/wcc.exe: 1: /home/jerry/.config/微信web开发者工具/WeappVendor/wcc.exe: MZ����@���: not found
/home/jerry/.config/微信web开发者工具/WeappVendor/wcc.exe: 1: /home/jerry/.config/微信web开发者工具/WeappVendor/wcc.exe: cannot open .text���: No such file
/home/jerry/.config/微信web开发者工具/WeappVendor/wcc.exe: 1: /home/jerry/.config/微信web开发者工具/WeappVendor/wcc.exe: 4���: not found
/home/jerry/.config/微信web开发者工具/WeappVendor/wcc.exe: 1: /home/jerry/.config/微信web开发者工具/WeappVendor/wcc.exe: .data
��@�.rdata0���@@.bssP�: not found
/home/jerry/.config/微信web开发者工具/WeappVendor/wcc.exe: 2: /home/jerry/.config/微信web开发者工具/WeappVendor/wcc.exe: l�Y�5�8���: not found
/home/jerry/.config/微信web开发者工具/WeappVendor/wcc.exe: 3: /home/jerry/.config/微信web开发者工具/WeappVendor/wcc.exe: Syntax error: word unexpected (expecting ")")

打开项目直接报该错误，执行了wxdt uninstall && wxdt install 还是不行，欢迎赐教，不胜感谢。

**Comment by jerryliu306** [comment]
已解决，删除/home/xxx/.cache/微信web开发者工具     缓存文件即可。
参考：https://github.com/cytle/wechat_web_devtools/issues/30

**Comment by q250305917** [comment]
我的删除了缓存还是不行...直接删掉重新拉取分支再试..

**Comment by q250305917** [comment]
删除了缓存  配置文件 项目  重新拉去分支安装还是不行....不知道哪个步骤错了ubuntu 16.04

**Comment by Sweetmile** [comment]
遇到相同问题 已解决
解决方法是进入root账号进行 uninstall 然后在普通账号去重新安装

**Comment by q250305917** [comment]
相同问题，同样解决了，我的是wine的版本问题，之前一直用的是2.02版本，后来替换成1.6的版本就正常了

**Comment by derekhe** [comment]
+1 果然是wine 2版本有问题

**Comment by brilliantree** [comment]
sudo apt-get install wine-binfmt
sudo update-binfmts --import /usr/share/binfmts/wine
