### ISSUE TITLE
关于字体更换

### ISSUE THREAD

**Issue by Sweetmile** [cytle/wechat_web_devtools#39]
默认字体很难看 想换掉 然而在菜单那儿点不动

**Comment by cytle** [comment]
检查到了`/package.nw/js/de640e457745362cd277fa7e893af981.js`这文件中,只支持`windows`和`mac`,本项目无法支持

**Comment by 13568810905** [comment]
所以没有办法修改字体了是吗？

**Comment by imknown** [comment]
Windows 也不能换 (Win7). 只能装一个 Windows 的 Consolas 字体...

**Comment by Honghe** [comment]
Ubuntu 可以下载这个 [Consolas.tff](https://github.com/kakkoyun/linux.files/blob/master/fonts/Consolas.ttf) 安装
