### ISSUE TITLE
./bin/update_package_nw.sh   更新小程序时，错误提示：./update_package_nw.sh: line 19: http: command not found

### ISSUE THREAD

**Issue by 04swjxy** [cytle/wechat_web_devtools#43]

**Comment by 04swjxy** [comment]
补充下。上面的问题解决了，是我没有安装httpie导致的。
现在安装好以后，报了另外一个错误。
http: error: ConnectionError: HTTPSConnectionPool(host='servicewechat.com', port=443): Max retries exceeded with url: /wxa-dev-logic/download_redirect?type=x64 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f0a7128bb50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

**Comment by 04swjxy** [comment]
不好意思，继续自问自答。上一个问题，是我自己网络不通的原因。
现在又碰到新的问题：我已经按照reademe的要求，把新版安装到了$HOME/.wine/drive_c/Program Files (x86)/Tencent/微信web开发者工具 目录下了。执行./bin/wxdt install后，再启动小程序，只会显示一个NW.JS的窗口，无法正确启动小程序，需要怎么办？（在下载新版本前，直接clone的代码之前已经能正常启动小程序）

**Comment by 04swjxy** [comment]
问题解决了，是我安装的时候，没有正确安装到 $HOME/.wine/drive_c/Program Files (x86)/Tencent/微信web开发者工具  目录下，导致的错误。后来我手动调整后就可以了。
建议是不是可以不要用 微信web开发者工具  这样的中文做目录，在linux下看着不习惯

**Comment by 04swjxy** [comment]
目录安装错误，应该是wine 安装时中文乱码引起的。建议将update_package_nw.sh脚本中的
wine $wcwd_file   修改为
env LC_ALL=zh_CN.UTF-8 wine $wcwd_file 
就可以解决wine安装中文乱码的问题

**Comment by cytle** [comment]
好的！多谢建议
