### ISSUE TITLE
如何生成桌面图标～

### ISSUE THREAD

**Issue by zuohuadong** [cytle/wechat_web_devtools#46]
下次启动直接从桌面打开

**Comment by yifan0817** [comment]
把打开的命令写成shell脚本，存到桌面文件目录下，再配个图就ok了。
参考资料： http://www.linuxidc.com/Linux/2013-06/86157.htm

**Comment by zqq90** [comment]
项目里面有个 `desktop.example`
改一下里面的路径, 然后后缀改成 `.desktop` 就可以了(顶多需要一次 F5)

**Comment by jmkylvy** [comment]
@zuohuadong     
在目录下面   $ ./bin/install_desktop.sh
