### ISSUE TITLE
运行  ./bin/wxdt 出错

### ISSUE THREAD

**Issue by MatchLemon** [cytle/wechat_web_devtools#49]
./nw: error while loading shared libraries: libnw.so: cannot open shared object file: No such file or directory

**Comment by Junup** [comment]
I had the same mistake, and no solution

**Comment by maxoyed-MS** [comment]
you can install the nwjs Manually

**Comment by jmkylvy** [comment]
@MatchLemon maybe you can try to clean your /tmp/wxdt_xsp directory, and then try ./bin/wxdt install again. 
good luck.

**Comment by foolifish07** [comment]
I thank there must be some network problem in your computer
if everything is downloaded well, `libnw.so` should be under `wechat_web_devtools/dist/lib`
So:
1. remove dist and rebuilt `rm -rf wechat_web_devtools/dist`
2. remove cache under `/tmp` `rm -rf /tmp/wxdt_xsp`

**Comment by beibeiroom** [comment]
My problem is "./nw: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory", I still cannot solution this question when I try to use the above way. By the way, my system is ubuntu18.04

**Comment by dashaomai** [comment]
if you meet the error message with keywords libgconf-2.so.4, you can try to do this: 
`sudo apt-get install libgconf-2-4`
