### ISSUE TITLE
开发者工具自动更新，导致失败。

### ISSUE THREAD

**Issue by sunraysun** [cytle/wechat_web_devtools#5]
`/home/sunray/wechat_web_devtools/package.nw/node_modules/node-windows/lib/node-windows.js:19
  throw 'ngn-windows is only supported on Windows.';
  ^
ngn-windows is only supported on Windows.
`

![screenshot_2017-05-21_10-04-40](https://cloud.githubusercontent.com/assets/10844/26280609/b3710f7e-3e0d-11e7-874a-a5f1d35ad154.png)

**Comment by cytle** [comment]
是使用开发者工具自带更新吗？现在不支持官方升级。

如果需要升级直接pull本项目就好了。现在版本是官方`0.17.170900`的代码

**Comment by sunraysun** [comment]
运行`./bin/wxdt` ，开发者工具启动后自己就更新了，能禁止自动更新吗？

**Comment by cytle** [comment]
应该是之前点了安装更新，现在我这个项目更新到`0.17.171900`版本,`pull`后启动试试，应该没有问题了。

**Comment by sunraysun** [comment]
已验证OK，多谢！
`git pull`后运行 `./bin/wxdt replace`覆盖后解决。
