### ISSUE TITLE
关于解决nwjs版本bug,系统是32位的小伙伴需要注意了

### ISSUE THREAD

**Issue by Missdeng** [cytle/wechat_web_devtools#51]
从bin目录下的update_nwjs.sh文件中贴一段代码出来.
`#! /bin/bash
# 下载nwjs，构建项目

root_dir=$(cd `dirname $0`/.. && pwd -P)

nwjs_v=`cat $root_dir/nwjs_v`
tmp_dir="/tmp/wxdt_xsp"

nwjs_file="$tmp_dir/nwjs-v$nwjs_v.tar.gz"
nwjs_dir="$tmp_dir/nwjs-sdk-v${nwjs_v}-linux-x64"
nwjs_download="https://dl.nwjs.io/v$nwjs_v/nwjs-sdk-v${nwjs_v}-linux-x64.tar.gz"

dist_dir="$root_dir/dist"`
很明显这里默认更新都是64位的nwjs版本，所以系统如果是64位的小伙伴要将这修改为32位地址哦!不然更新下来，你的软件可能又有问题了。具体对应的版本链接可以参看这里的下载路径https://nwjs.io/

**Comment by cytle** [comment]
不错，没有考虑到32位系统的小伙伴。

**Comment by cytle** [comment]
已经增加，https://github.com/cytle/wechat_web_devtools/commit/69b9e43c5b20046e0739ef139b948d42d3b51dc9
