### ISSUE TITLE
调试版不显示

### ISSUE THREAD

**Issue by Missdeng** [cytle/wechat_web_devtools#52]
想问下楼主，为何装上之后调试版不显示，是还需要安装什么？

**Comment by cytle** [comment]
方便上下截图吗，不太理解问题

**Comment by Missdeng** [comment]
![2017-12-03 13-34-01](https://user-images.githubusercontent.com/12594922/33522800-e95fbdc0-d830-11e7-984b-15ff45815279.png)

您好，如图中所示，调试器部分空白显示，不知道哪里js文件还是html文件没执行;
环境：ubuntu 16.04.3LTS（32位）

**Comment by yifan0817** [comment]
打开方式不对吧   我之前也遇到过   没有按楼主说的方式安装

**Comment by Missdeng** [comment]
安装命令都是按照楼主的的，但是有部分由于楼主的针对没有32位系统，所以我修改了bash文件

**Comment by cytle** [comment]
@Missdeng 手边没有32位的环境，可能需要你自己的支持了。

可以把这些发上来
1. 终端有没有什么输出
2. 执行`./bin/wxdt` 打开 http://localhost:9222，看下上面有没有异常

另外可以尝试依次切换nwjs版本
1. 在https://dl.nwjs.io/找一个版本
2. 修改目录下面nwjs_v文件为新版本号
3. 执行`./bin/update_nwjs`

祝你好运

**Comment by Missdeng** [comment]
楼主，谢谢，我找到问题所在了，我将nwjs版本改为了0.26.6没想到才导致这个问题，换回了0.24.4版本问题解决了 。
