### ISSUE TITLE
小程序出问题

### ISSUE THREAD

**Issue by jmkylvy** [cytle/wechat_web_devtools#53]
编译.wxml文件错误：
run-detectors: unable to find an interpreter for /home/jm/.config/微信web开发者工具/WeappVendor/wcc.exe

wine-2.18

**Comment by cytle** [comment]
按步骤重新安装即可

**Comment by jmluang** [comment]
今天又遇到这个问题了。。 试过uninstall再install 还是不行，我记得上个版本是可以的
run-detectors: unable to find an interpreter for /home/jm/wechat_web_devtools/package.nw/js/vendor/wcc.exe

**Comment by cytle** [comment]
看上去文件路径是没错的。可以尝试下完全删除再安装

**Comment by jmluang** [comment]
试过重新clone install，还是有这个问题。。。有可能是我的wine版本不对？我的wine是wine-development

**Comment by cytle** [comment]
有可能，尝试直接执行下
1.  `.config/微信web开发者工具/WeappVendor/wcc.exe` 
2.  `.config/微信web开发者工具/WeappVendor/s/wcc.exe` 实际上它是硬链接自3
3.  `wechat_web_devtools/package.nw/js/vendor/wcc.exe`
