### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by izern** [cytle/wechat_web_devtools#56]
![image](https://user-images.githubusercontent.com/17672970/34553790-56049cce-f164-11e7-8548-5a41184ca3cc.png)
代码是腾讯云官网demo，Windows下可以运行的。
https://cloud.tencent.com/document/product/454/7873#XiaoChengXu

**Comment by cytle** [comment]
终端有什么错误吗？

或者可以完全退出开发者工具，再启动试下。

**Comment by izern** [comment]
[4869:4891:0105/111446.772718:ERROR:nss_util.cc(802)] After loading Root Certs, loaded==false: NSS error code: -8018
** Message: Remote error from secret service: org.freedesktop.DBus.Error.UnknownMethod: 在路径 org.freedesktop.Secret.Collection 的对象上没有 /org/freedesktop/secrets/collection/login 接口

**Comment by izern** [comment]
使用终端启动，报的错误。
新建一个项目，是可以正常预览的

**Comment by izern** [comment]
重新点击编译，控制台出现：
[5110:5110:0105/111719.532689:ERROR:CONSOLE(4815)] "Cannot find context with specified id", source: chrome-devtools://devtools/bundled/inspector.js (4815)
[5110:5110:0105/111719.532741:ERROR:CONSOLE(7305)] "Extension server error: Inspector protocol error: Cannot find context with specified id", source: chrome-devtools://devtools/bundled/inspector.js (7305)

界面依旧是上图异常

**Comment by cytle** [comment]
不好意思，这么晚才回复，刚跑了一遍发现可以编译的,控制台的错误和此无关，你再试一次

**Comment by cytle** [comment]
今天又打开了，发现的确不能编译。。

**Comment by fozoto** [comment]
我也出现了同样的问题, 报错如下:
./bin/wxdt start
[10737:10737:0114/162927.679796:ERROR:gl_implementation.cc(246)] Failed to load /soft/wechat_web_devtools-1.02.1801081/dist/swiftshader/libGLESv2.so: /soft/wechat_web_devtools-1.02.1801081/dist/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory

解决方案:
下载1.02.1801081版本, 后引库
$ mkdir -p /soft/wechat_web_devtools-1.02.1801081/dist/swiftshader
$ cp /usr/lib/chromium-browser/swiftshader/libEGL.so /soft/wechat_web_devtools-1.02.1801081/dist/swiftshader
$ cp /usr/lib/chromium-browser/swiftshader/libGLESv2.so /soft/wechat_web_devtools-1.02.1801081/dist/swiftshader

**Comment by fozoto** [comment]
只要新建component, 还是会出现同样的问题

**Comment by 316boss** [comment]
我也遇到了同样的问题，请问解决了吗？

**Comment by TAUnionEd** [comment]
+1 :sob:

**Comment by Andyliwr** [comment]
@cytle 能找到解决方案吗？

**Comment by fozoto** [comment]
以前安装wine是按着wine官网sudo apt-get install --install-recommends winehq-stable安装的, 不能设置为32位的: wine: WINEARCH set to win32 but '/home/qingyan/.wine' is a 64-bit installation.
  看到上面的仁兄说成功了, 我也试了试, 确实成功了:
  先卸载sudo apt-get remove --install-recommends winehq-stable
  然后完全按着作者的安装步骤, 成功了, 新建component也不会报错了
![image](https://user-images.githubusercontent.com/34918133/35196055-00438302-ff08-11e7-91b8-978990a29537.png)

**Comment by LiJoah** [comment]
我安装最新的版本，得到一个错误，导致我安装不上，不知道是什么原因



问题：
please wait 5s!
./nw: error while loading shared libraries: libnw.so: cannot open shared object file: No such file or directory
1s
2s
3s
4s
5s
kill nw
/home/liyao/wechat_web_devtools-1.01.1711160/bin/replace_weapp_vendor.sh: 第 19 行: kill: (8028) - 没有那个进程
Error: 开发者工具未生成文件夹 /home/liyao/.config/微信web开发者工具, 可能是权限问题, 请参考项目issue
Fail! Please reinstall
安装完成

**Comment by qq942159888** [comment]
Error:
env: wine: 没有那个文件或目录
编译 .wxml 文件错误，错误信息如上，可在控制台查看更详细信息

**Comment by 316boss** [comment]
@fozoto 你好，我想问下，你装的是 wine1.8 吗？我用的 ubuntu 17.04，apt install 装的话最低都是 2.0.2 了

**Comment by breeze0** [comment]
@LiJoah 你好  你那个问题解决了吗

**Comment by cytle** [comment]
@izern 不能编译腾讯云demo的原因找到了，如 @fozoto  所说是自定义组件(Component)造成的。

解决方案还没有找到，可以参考他的方法试试。

**Comment by cytle** [comment]
升级了最新版本后，这个问题好像被解决了，@all

**Comment by card0106** [comment]
编译一直出错，
![2018-02-12 17-03-54](https://user-images.githubusercontent.com/10581955/36089439-e36dbd54-1016-11e8-95a5-e0fc1a162ebb.png)

**Comment by cytle** [comment]
@card0106 我这没有出现此问题，你要不试下重新安装

**Comment by kafukwen** [comment]
我也出现这个楼上中文乱码问题

**Comment by 316boss** [comment]
我也遇到了这个问题，我猜可能是 wine 版本的问题，ubuntu 17.10 貌似不支持 1.8 了，现在装的是更高版本的 wine

**Comment by fozoto** [comment]
@316boss 我的是ubuntu16.04
$ wine --version
wine-3.0

**Comment by tengqian** [comment]
我用小程序的时候发现启动就报找不到wcc.exe 和wcsc.exe 这个安照项目介绍的步骤 做完之后把 /home/XXX/.config/微信web开发者工具/WeappVendor 这个目录下的东西复制到安装目录下 /wechat_web_devtools/package.nw/js/vendor/ 下进行替换就可以使用了 希望对之后的人有帮助 已更新到1.02.1802080 版本

**Comment by Hrysa** [comment]
![](https://user-images.githubusercontent.com/10581955/36089439-e36dbd54-1016-11e8-95a5-e0fc1a162ebb.png)
遇到了这个问题，解决办法是
`cd /path/wechat_web_devtools`

备份 (如果不起作用可以还原回来)
`mv package.nw/js/vendor/wcc.exe  package.nw/js/vendor/wcc.exe.old`
`mv package.nw/js/vendor/wcsc.exe package.nw/js/vendor/wcsc.exe.old`

`cp -rf bin/WeappVendor/* package.nw/js/vendor/`

搞定~
希望作者能测试下这个bug

**Comment by 316boss** [comment]
@Hrysa 这么做等于是降级了，上面提到的编译出错的问题又会出现

**Comment by Hrysa** [comment]
@316boss 你指的是哪个错误啊？

**Comment by cytle** [comment]
我这一直没有这问题，我猜测如同 @Hrysa 所讲是因为`wcc.exe`和`wcsc.exe`没有正确的拷贝到`~/.config/微信web开发者工具`下造成的，按以下步骤解决

1. 执行
```shell
wine ~/.config/微信web开发者工具/WeappVendor/s/wcc.exe
```

 结果应该如下, 如果提示没有该文件，则跳到第3步，如果是wine错误则继续第2步
```
Wechat WXML Compiler, version v0.6vv_20180111_fbi
Usage: \home\xsp\.config\微信web开发者工具\WeappVendor\s\wcc.exe [-d] [-o OUTPUT] [-xc XComponentDefine] [-om XComponentDefine] <FILES... | -s <SINGLE_FILE>
  Options:
  -d: output code for debug
  -o: output destination (default stdout)
 -xc: output simplified code for custom component
 -cc: output compelete code for custom component
  -s: read from stdin
XComponentDefine:
	'<wxml_count> <<wxml_path_i> <xcompo_count> <xcompos...> ...>
	example: '2 /page/index.wxml 2 mytag mygame /page/log.wxml 1 mytag'
```

2.  执行替代脚本

```shell
sh ~/.config/微信web开发者工具/WeappVendor/wcc.exe
```

结果应该和第一步正常结果一样，如果错误，可能是`wine`安装错误，也有可能是其他错误，贴到这个issue下。

3. 执行该项目下的`replace_weapp_vendor.sh`,替换`*.exe`

```shell
./bin/replace_weapp_vendor.sh
```
如果上面这条执行错误，手动拷贝
```shell
cp -rf ./bin/WeappVendor/* ~/.config/微信web开发者工具/WeappVendor
```



ps: `wine`错误可以测试新版本`wine`, 相关issue https://github.com/cytle/wechat_web_devtools/issues/66

**Comment by tangmingming** [comment]
@cytle   我的也报这个错误（run-detectors: unable to find an interpreter for /home/tmm/.config/微信web开发者工具/WeappVendor/wcc.exe）
我觉得应该是WINEARCH=win32 WINEPREFIX=~/.wine32 winecfg 这步哪儿错了  是否可以把这步写的清除点呢   我ubuntu执行这条会弹出一个对话框 有很多配置

**Comment by cytle** [comment]
@tangmingming 能正确执行`wine ~/.config/微信web开发者工具/WeappVendor/s/wcc.exe`这条命令吗

**Comment by tangmingming** [comment]
@cytle  我去  什么鬼   重新安装一遍  执行一下你说的 wine ~/.config/微信web开发者工具/WeappVendor/s/wcc.exe   再打开就可以了 O(∩_∩)O哈哈~

**Comment by goldenfreemanchina** [comment]
@Hrysa 试了，但是依然存在问题 ubuntu17.10   wine用了apt的stable1.8  和wineHQ PPA的3.0问题依然；表示累觉换win10了...

**Comment by goldenfreemanchina** [comment]
@cytle 执行  `wine ~/.config/微信web开发者工具/WeappVendor/s/wcc.exe`   

得到的是 `wine: cannot find '/.config/΢��web�����߹���/WeappVendor/s/wcc.exe'`

**Comment by goldenfreemanchina** [comment]
@cytle -_-!!!弄了一个礼拜了...结果就差这一行  ` ./bin/replace_weapp_vendor.sh`

**Comment by Sir-H** [comment]
@cytle sudo ./bin/wxdt           

(process:4687): Gtk-WARNING **: Locale not supported by C library.
        Using the fallback 'C' locale.
[4687:4718:0313/185056.936888:ERROR:data_store_impl.cc(131)] Failed to open Data Reduction Proxy DB: 3
无法运行，

**Comment by cytle** [comment]
@Sir-H 这错误没见过，应该是wcc编译错误造成的，另外开一个issue吧

**Comment by cytle** [comment]
@goldenfreemanchina 哈哈，我一直以为是wine错误，结果是没移进去，抱歉浪费你一周时间。

@all 看来这个issue可以关闭了

**Comment by cytle** [comment]
尝试下 https://github.com/cytle/wechat_web_devtools/issues/56#issuecomment-371999385 看看哪步出了问题

**Comment by Zack-Bee** [comment]
Ubuntu 16.04
wine 3.5
@cytle 

> 执行1
> wine ~/.config/微信web开发者工具/WeappVendor/s/wcc.exe

没有问题

然后执行2

> 执行替代脚本
> sh ~/.config/微信web开发者工具/WeappVendor/wcc.exe

出现错误
`/home/zackbee/.config/微信web开发者工具/WeappVendor/wcc.exe: 1: /home/zackbee/.config/微信web开发者工具/WeappVendor/wcc.exe: MZ����@���: not found
/home/zackbee/.config/微信web开发者工具/WeappVendor/wcc.exe: 2: /home/zackbee/.config/微信web开发者工具/WeappVendor/wcc.exe: cannot open .text�.data�0@�.rdata��@�*@@.bssP�: No such file
/home/zackbee/.config/微信web开发者工具/WeappVendor/wcc.exe: 2: /home/zackbee/.config/微信web开发者工具/WeappVendor/wcc.exe: ��qZ�7�
                                                        8�: not found
/home/zackbee/.config/微信web开发者工具/WeappVendor/wcc.exe: 3: /home/zackbee/.config/微信web开发者工具/WeappVendor/wcc.exe: Syntax error: word unexpected (expecting ")")
`

执行3

> 执行该项目下的replace_weapp_vendor.sh,替换*.exe
./bin/replace_weapp_vendor.sh

然后再执行2, 正常运行, 启动开发者工具, 编译后依旧出现错误

`/home/zackbee/.config/微信web开发者工具/WeappVendor/wcc.exe: 1: /home/zackbee/.config/微信web开发者工具/WeappVendor/wcc.exe: MZ����@���: not found
/home/zackbee/.config/微信web开发者工具/WeappVendor/wcc.exe: 2: /home/zackbee/.config/微信web开发者工具/WeappVendor/wcc.exe: cannot open .text�.data�0@�.rdata��@�*@@.bssP�: No such file
/home/zackbee/.config/微信web开发者工具/WeappVendor/wcc.exe: 2: /home/zackbee/.config/微信web开发者工具/WeappVendor/wcc.exe: ��qZ�7�
                                                        8�: not found
/home/zackbee/.config/微信web开发者工具/WeappVendor/wcc.exe: 3: /home/zackbee/.config/微信web开发者工具/WeappVendor/wcc.exe: Syntax error: word unexpected (expecting ")")
`

此时关闭开发者工具, 执行2, 出现错误
`/home/zackbee/.config/微信web开发者工具/WeappVendor/wcc.exe: 1: /home/zackbee/.config/微信web开发者工具/WeappVendor/wcc.exe: MZ����@���: not found
/home/zackbee/.config/微信web开发者工具/WeappVendor/wcc.exe: 2: /home/zackbee/.config/微信web开发者工具/WeappVendor/wcc.exe: cannot open .text�.data�0@�.rdata��@�*@@.bssP�: No such file
/home/zackbee/.config/微信web开发者工具/WeappVendor/wcc.exe: 2: /home/zackbee/.config/微信web开发者工具/WeappVendor/wcc.exe: ��qZ�7�
                                                        8�: not found
/home/zackbee/.config/微信web开发者工具/WeappVendor/wcc.exe: 3: /home/zackbee/.config/微信web开发者工具/WeappVendor/wcc.exe: Syntax error: word unexpected (expecting ")")
`

**Comment by gooqiao** [comment]
@fozoto ，感谢。根据你的方法成功安装，编译小程序通过。

**Comment by mx52jing** [comment]
Ubuntu 16.04 
试了上面的方法都不行
错误如下
```
/home/t8l7j2/.config/微信web开发者工具/WeappVendor/wcc.exe: 1: /home/t8l7j2/.config/微信web开发者工具/WeappVendor/wcc.exe: MZ����@���: not found
/home/t8l7j2/.config/微信web开发者工具/WeappVendor/wcc.exe: 2: /home/t8l7j2/.config/微信web开发者工具/WeappVendor/wcc.exe: cannot open .text�.data�0@�.rdata��@�*@@.bssP�: No such file
/home/t8l7j2/.config/微信web开发者工具/WeappVendor/wcc.exe: 2: /home/t8l7j2/.config/微信web开发者工具/WeappVendor/wcc.exe: ��qZ�7�
                                       8�: not found
/home/t8l7j2/.config/微信web开发者工具/WeappVendor/wcc.exe: 3: /home/t8l7j2/.config/微信web开发者工具/WeappVendor/wcc.exe: Syntax error: word unexpected (expecting ")")

```
![1302387401](https://user-images.githubusercontent.com/22701464/39183181-c1c7d2b2-47f1-11e8-88de-8a3834f3b557.jpg)

**Comment by wangyetao** [comment]
![2018-05-29 20-33-52](https://user-images.githubusercontent.com/32868808/40660435-93cb2172-6383-11e8-8542-96f047de324d.png)

/home/wangyetao/Download/wechat_web_devtools/package.nw/js/vendor/wcc.exe: 1: /home/wangyetao/Download/wechat_web_devtools/package.nw/js/vendor/wcc.exe: MZ����@���: not found
/home/wangyetao/Download/wechat_web_devtools/package.nw/js/vendor/wcc.exe: 2: /home/wangyetao/Download/wechat_web_devtools/package.nw/js/vendor/wcc.exe: cannot open .text�.data�0@�.rdata��@�*@@.bssP�: No such file
/home/wangyetao/Download/wechat_web_devtools/package.nw/js/vendor/wcc.exe: 2: /home/wangyetao/Download/wechat_web_devtools/package.nw/js/vendor/wcc.exe: �qZ�7�8�: not found
/home/wangyetao/Download/wechat_web_devtools/package.nw/js/vendor/wcc.exe: 3: /home/wangyetao/Download/wechat_web_devtools/package.nw/js/vendor/wcc.exe: Syntax error: word unexpected (expecting ")")

**Comment by cytle** [comment]
执行项目下的replace_weapp_vendor.sh试试

```bash
./bin/replace_weapp_vendor.sh
```

**Comment by reec20** [comment]
试试这个
Update the package index:
# sudo apt-get update
Install wine deb package:
# sudo apt-get install wine

**Comment by Zack-Bee** [comment]
> 执行项目下的replace_weapp_vendor.sh试试

> ./bin/replace_weapp_vendor.sh
执行之后能够正常运行`sh ~/.config/微信web开发者工具/WeappVendor/wcc.exe`, 但是打开小程序的开发者工具依旧会报错 @cytle

**Comment by run27017** [comment]
@cytle 按照你的步骤：

> 执行1
> wine ~/.config/微信web开发者工具/WeappVendor/s/wcc.exe

没有问题

然后执行2

> 执行替代脚本
> sh ~/.config/微信web开发者工具/WeappVendor/wcc.exe

出现错误：

> /home/hello/.config/微信web开发者工具/WeappVendor/wcc.exe: /home/hello/.config/微信web开发者工具/WeappVendor/wcc.exe: 无法执行二进制文件

另外，这个[链接](https://pkgs.org/download/wine-binfmt)的wine-binfmt下载，找不到rpm包的安装包，只有debain和ubuntu的。

也不能这么说，有ROSA的rpm包，但放在我的openSuse系统上不能用。

**Comment by liangxp9221** [comment]
@Hrysa 的降级做法我成功了.

**Comment by liangxp9221** [comment]
@Zack-Bee 貌似是bin/WeappVender/*下的exe文件是不会乱码的，但是package.nw/js/vender/下则是乱码，执行bin/wxdt是拷贝package.nw/js/vender/的wcc.exe和wcsc.exe。所以发生你这个问题。
所以你先要按@Hrysa的做法先降级，然后再按作者的做法就可以了。

**Comment by Zack-Bee** [comment]
非常感谢, 不过我现在已经投入win10的怀抱了

liangxp9221 <notifications@github.com> 于2018年7月24日周二 上午10:46写道：

**Comment by Tooooommy** [comment]
可以添加自己添加wine-binfmt：
https://blog.izgq.net/archives/1008/

**Comment by zyzhuzai** [comment]
编译没有报错，但是，页面没有显示任何内容，这个，是咋回事呢？？有没有哪位大佬遇到这问题啊

**Comment by kun-guo** [comment]
deepin 自定义组件无法识别

**Comment by Funny-dot** [comment]
/root/.config/wechat_web_devtools/WeappVendor/wcc.exe: 1: /root/.config/wechat_web_devtools/WeappVendor/wcc.exe: MZ锟?锟斤拷锟紷锟?锟?锟? not found
/root/.config/wechat_web_devtools/WeappVendor/wcc.exe: 3: /root/.config/wechat_web_devtools/WeappVendor/wcc.exe: Syntax error: word unexpected (expecting ")")

大佬们，这个咋处理啊   非常感谢

**Comment by Funny-dot** [comment]
wine ~/.config/wechat_web_devtools/WeappVendor/s/wcc.exe
wine: Bad EXE format for Z:\root\.config\wechat_web_devtools\WeappVendor\s\wcc.exe.
