### ISSUE TITLE
添加component组件时报错

### ISSUE THREAD

**Issue by SnowsonZ** [cytle/wechat_web_devtools#58]
![2018-01-24 22-35-49](https://user-images.githubusercontent.com/12555482/35338351-a427d19c-0158-11e8-8256-eb9c26482d08.png)

**Comment by SnowsonZ** [comment]
![2018-01-24 22-35-49](https://user-images.githubusercontent.com/12555482/35338281-72cd0e0a-0158-11e8-81cf-279ca8176147.png)

**Comment by jeasonzs** [comment]
我也发现这个问题了，暂时降级到v1.01.1711160 好了

**Comment by cytle** [comment]
同 https://github.com/cytle/wechat_web_devtools/issues/56， 都是编译component失败造成的
