### ISSUE TITLE
libnw.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ydw1118** [cytle/wechat_web_devtools#59]
david@david-pc /o/wechat_web_devtools> sudo ./bin/wxdt
[sudo] david 的密码： 
安装微信开发者工具对应nwjs版本：0.24.4
update nwjs success
./nw: error while loading shared libraries: libnw.so: cannot open shared object file: No such file or directory执行的时候报这个错。

**Comment by cytle** [comment]
参考 https://github.com/cytle/wechat_web_devtools/issues/49
