### ISSUE TITLE
找不到设置入口

### ISSUE THREAD

**Issue by colorwin** [cytle/wechat_web_devtools#6]
在左上角找不到设置入口，只有代理可以设置，在按alt键也没反应

**Comment by cytle** [comment]
你说的设置我一直没发现在哪。windows下是咋样的？

**Comment by cytle** [comment]
ha，明白你什么意思了，我试试能不能给加上

**Comment by cytle** [comment]
pull 下可以看到以下菜单

![image](https://cloud.githubusercontent.com/assets/5120505/26318716/a68d6454-3ee1-11e7-823d-07b9cce53b2e.png)
