### ISSUE TITLE
新版本远程调试提示 Error: node-sync-ipc is broken.

### ISSUE THREAD

**Issue by cytle** [cytle/wechat_web_devtools#60]
点击远程调试后，提示
```
Error: node-sync-ipc is broken.
```

**Comment by cytle** [comment]
原因找到了，在linux环境下，包`node-sync-ipc`加载其下的二进制文件`build/Release/server.node`失败

```
Error: /home/xsp/wechat_web_devtools/package.nw/node_modules/node-sync-ipc/build/Release/server.node: æ æç ELF å¤´
    at Object.Module._extensions..node (module.js:644)
    at Module.load (module.js:531)
    at tryModuleLoad (module.js:494)
    at Function.Module._load (module.js:486)
    at Module.require (module.js:541)
    at require (internal/module.js:11)
    at Object.<anonymous> ([ipc/parent]:1)
    at Module._compile (module.js:597)
    at Object.Module._extensions..js (module.js:614)
    at Module.load (module.js:531)
```

**Comment by mohuishou** [comment]
这个包需要在的linux下面重新编译，然后替换掉`node-sync-ipc`和`node-sync-ipc-nw`目录下的`build`文件夹

但是替换之后仍然会报错
```
Error: spawn /home/lxl/soft/wechat_web_devtools/dist/node.exe ENOENT
```
暂时不知道为什么会调用node.exe

**Comment by MMhunter** [comment]
这个修复了吗？没想到被微信开发工具临幸了

重新测试了一下，在linux下面重新编译的单独node-sync-ipc库没有发现问题。

应该还是要经nw重新编译才能正常使用

@mohuishou 提到的错误应该是在使用childProcess.fork时产生的，微信工具内的node-sync-ipc的lib部分被微信团队修改过，如果用原库里面的lib替换会出问题，不知道是否和这个相关

**Comment by cytle** [comment]
哈哈，还没有修复，这个项目是非官方项目，我原本以为你是微信内部人员呢。

现在库的源码还是能看到的，[node_modules/node-sync-ipc](https://github.com/cytle/wechat_web_devtools/tree/master/package.nw/node_modules/node-sync-ipc)，就不懂怎么修改

**Comment by MMhunter** [comment]
他们没有修改c++的部分，理论上是只要在linux下用node-gyp重新编译node-sync-ipc，用nw-gyp重新编译node-sync-ipc-nwjs替换掉就好

**Comment by MMhunter** [comment]
啊等等。。

仔细看过源码之后。。他在isMac变量是true的时候调用了node-sync-ipc, 在是false的时候调用了node-sync-ipc-nwjs。。。并且mac的微信工具里面没有node-sync-ipc-nwjs，怀疑是不是在unix系统下面只要用node-gyp编译的就好了

**Comment by MMhunter** [comment]
尝试着提交了一个当前版本的修复PR，但是这个只是一个简单修复思路，为了防止每次微信那边更新都要重新弄一便，可能要写些脚本做些事情：

1. 把库重新编译
2. 要让源码里面所有判断是否darwin的语句的在linux下面选择正确的分支

另外在dist里新增了一个node执行文件，好像远程调试功能就是要用到的

**Comment by cytle** [comment]
运行了，修复PR能够解决问题。已经合并到master

1.  node-sync-ipc和node-sync-ipc-nwjs问题,可以用脚本直接替换node-sync-ipc-nwjs为node-sync-ipc
2.  库重新编译可以放在包install时做，兄弟帮我弄一个支持的linux的包，我给项目添加一个依赖

另外

-   node执行文件可以使用用户本地的吗

**Comment by MMhunter** [comment]
其实我觉得如果之后不变的话，可以就直接保留现在node_modules/node-ipc-sync/build下面的文件，以后覆盖就好了

node这个就不清楚了，代码里面默认调用的是 {程序执行路径}/node（本来是windows的话是node.exe), 所以最后是在dist里面，也许你可以在nw生成dist的时候检查usr/bin/node，如果版本满足就复制过去？

**Comment by cytle** [comment]
@MMhunter 😆这样复制不太好吧，之后计划打成npm包发布。昨天晚上用[nw](https://www.npmjs.com/package/nw)这个包运行项目，发现`node-ipc-sync`调用的是`node_modules/nw/bin/node`, 这样复制就有问题😆😆😆😆。

**Comment by MMhunter** [comment]
这个node不是我那个node-sync-ipc调用的=。=， 是微信开发工具里面远程调试功能要用到

我那个node-sync-ipc is broken问题其实只要是重新编译一遍就解决了

微信混淆后的源码[这个文件(现在是修改后了)](https://github.com/MMhunter/wechat_web_devtools/blob/36901e056b7e8128a0817e352636167255ee0e30/package.nw/js/6c6f4dde020ed24929c4c4367c42d34d.js)里面写的是类似运行execPath+"node"+(isMac)?"":".exe"，所以用nw运行估计就是nw的运行目录了....

**Comment by cytle** [comment]
原来是这样，明白了

**Comment by reesexu** [comment]
@cytle @MMhunter 这个问题我还是复现了哦。ubuntu16.04。请问两位哥有什么解决办法吗

**Comment by gangbanbro** [comment]
新版又有此问题了。执行fix脚本也无效，依然报错。
deepin系统

**Comment by ytang625** [comment]
又出现了这个问题，ubuntu 16.04

**Comment by tulongxCodes** [comment]
MAC pro 同样问题
![image](https://user-images.githubusercontent.com/12908403/61919207-1c321200-af87-11e9-9399-7a0c430172d7.png)
