### ISSUE TITLE
开发工具编译错误

### ISSUE THREAD

**Issue by pjyong** [cytle/wechat_web_devtools#65]
`run-detectors: unable to find an interpreter for /home/june/.config/微信web开发者工具/WeappVendor/wcc.exe`

开发工具编译就会报错，请问如何让开发工具配置wine打开方式？

**Comment by pjyong** [comment]
已经解决。
这个不属于开发工具的问题，而是系统没有将设置exe默认打开方式(虽然我已经右键设置了默认打开方式)，比如在命令行里执行 ./xxx.exe时，就会报上面的错误。
可以执行下面的命令解决此问题
`sudo apt-get install wine-binfmt`
 `sudo update-binfmts --import /usr/share/binfmts/wine`

**Comment by armyja** [comment]
非常感谢！

**Comment by QQ876684433** [comment]
我也遇到过这个问题，Ubuntu17.10，按照上面的做法不能解决，因为他和deepinwine冲突了，我重新安装了一遍wine
sudo apt-get install wine-stable
然后再重新编译项目，就成了

**Comment by legend-zl** [comment]
使用wine-binfmt的方式解决了，真的太感谢。555
