### ISSUE TITLE
不用创建32位wine环境也能编译

### ISSUE THREAD

**Issue by levinit** [cytle/wechat_web_devtools#66]
我没有执行`WINEARCH=win32 WINEPREFIX=~/.wine32 winecfg`也能编译成功呢 反馈一下
系统64位archlinux wine3.2

**Comment by levinit** [comment]
顺便问一下wine-mono和wine_gecko依赖问题 在archlinux中wine wine-mono wine_gecko是三个包 虽然winecfg会提示安装wine_gecko（此时点击安装，会自动下载安装而非以包管理器安装），不过点击不安装也不会影响什么。我打了个aur包，不知道wine_gecko是否有必要加到依赖中。

**Comment by jmluang** [comment]
我装了wine1.6创建32位wine环境还是编译.wxml文件错误。ubuntu17.10 郁闷~

**Comment by levinit** [comment]
@jmluang  兄弟 还1.6啊 至少来个1.8吧 3.2默默看着你
```shell
~ $ wine --version
wine-3.2
```

**Comment by cytle** [comment]
现在我设备上用的也是wine 3.2  64x，没有太多实验，不确定兼容性。主要还是推荐1.8。

@jmluang 可以尝试下wine 3.2  64x

@levinit `wine-mono`和`wine_gecko`这两个包现在看来不是必需的。

> 安装 wine_gecko 和 wine-mono 软件包。它们分别用于运行依赖于 Internet Explorer 和 .NET 的程序。不过，也可以随后通过 Wine 在需要时下载安装这些组件。但如果提前下载安装，您就可以离线使用它们，而且 Wine 不必为了每一个 WINEPREFIX 都单独下载。
> -- https://wiki.archlinux.org/index.php/Wine_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)

**Comment by jmluang** [comment]
被wcc.exe的编译问题折腾了好久，终于没问题了。。记录下我的解决办法吧 :)
（OS: Ubuntu 17.10 artful , wine-3.0）
1. 在安装前先执行命令 ` wine /path/to/wechat_web_devtools/package.nw/js/vendor/wcc.exe `，看是否能运行，看有没有依赖要装上。若正常运行应该会显示这些
```
Wechat WXML Compiler, version v0.6vv_20180111_fbi
Usage: Z:\home\jm\wechat_web_devtools\package.nw\js\vendor\wcc.exe [-d] [-o OUTPUT] [-xc XComponentDefine] [-om XComponentDefine] <FILES... | -s <SINGLE_FILE>
  Options:
  -d: output code for debug
  -o: output destination (default stdout)
 -xc: output simplified code for custom component
 -cc: output compelete code for custom component
  -s: read from stdin
XComponentDefine:
	'<wxml_count> <<wxml_path_i> <xcompo_count> <xcompos...> ...>
	example: '2 /page/index.wxml 2 mytag mygame /page/log.wxml 1 mytag'
``` 
2. 若仍旧不行的朋友可以试试下面两条命令，注意需要先uninstall
` $ sudo apt-get install wine-binfmt `
` $ sudo update-binfmts --import /usr/share/binfmts/wine `

**Comment by levinit** [comment]
Ubuntu装wine这么麻烦呀😂 依赖这些安装时不时应该都自己连带装上嘛



在 jm <notifications@github.com>，2018年2月26日 下午5:08写道：

被wcc.exe的编译问题折腾了好久，终于没问题了。。记录下我的解决办法吧 :)
（OS: Ubuntu 17.10 artful , wine-3.0）

  1.  在安装前先执行命令 wine /path/to/wechat_web_devtools/package.nw/js/vendor/wcc.exe，看是否能运行，看有没有依赖要装上。若正常运行应该会显示这些

Wechat WXML Compiler, version v0.6vv_20180111_fbi
Usage: Z:\home\jm\wechat_web_devtools\package.nw\js\vendor\wcc.exe [-d] [-o OUTPUT] [-xc XComponentDefine] [-om XComponentDefine] <FILES... | -s <SINGLE_FILE>
  Options:
  -d: output code for debug
  -o: output destination (default stdout)
 -xc: output simplified code for custom component
 -cc: output compelete code for custom component
  -s: read from stdin
XComponentDefine:
        '<wxml_count> <<wxml_path_i> <xcompo_count> <xcompos...> ...>
        example: '2 /page/index.wxml 2 mytag mygame /page/log.wxml 1 mytag'


  1.  若仍旧不行的朋友可以试试下面两条命令，注意需要先uninstall
$ sudo apt-get install wine-binfmt
$ sudo update-binfmts --import /usr/share/binfmts/wine

**Comment by imknown** [comment]
@jmluang 
貌似执行完命令, 然后点一下 <kbd>编译</kbd> 就可以啦...

``` bash
sudo apt-get install wine-binfmt
sudo update-binfmts --import /usr/share/binfmts/wine
```

我 `wine 3.4 x64`, `Xubuntu`, `英文`.

**Comment by EasonShi** [comment]
wine-binfmt 找不到的话， 也可以单独下载
https://pkgs.org/download/wine-binfmt
