### ISSUE TITLE
更新到v0.17.171900后不能自动监听刷新了，编译快捷键无效

### ISSUE THREAD

**Issue by colorwin** [cytle/wechat_web_devtools#7]
更新到v0.17.171900后不能自动监听刷新，在上一版是可以的。另外，快捷键Ctrl+b编译，也没反应

**Comment by colorwin** [comment]
应该和设置有关， 我保留了旧的"~/.config/微信web开发者工具"里面的设置数据，把旧的恢复又可以自动监听了。

**Comment by cytle** [comment]
设置界面有了，参考你的另一个issue，快捷键这问题我再看看

**Comment by colorwin** [comment]
“Shift+Ctrl+A”快捷键选取元素也不行，应该是同一个issue

**Comment by levinit** [comment]
新的可以设置自动保存 不过好像是几秒自动保存一次 这时候会刷新

**Comment by cytle** [comment]
@colorwin Ctrl+b快捷键可以了

“Shift+Ctrl+C”快捷键选取元素不行，找不到相关的地方，应该不会修复了。
