### ISSUE TITLE
更新开发者工具时提示http: not found

### ISSUE THREAD

**Issue by crystoy** [cytle/wechat_web_devtools#72]
update_package_nw.sh: 19: update_package_nw.sh: http: not found
下载版本为空
系统:deepin 15.5(debian sid)
是缺少个包？我看之前的issues里有提到这个问题，但貌似没解决。版本号人工填上可以顺利更新，麻烦看下，谢谢。

**Comment by cytle** [comment]
安装上就好了， https://httpie.org/doc#linux

**Comment by crystoy** [comment]
好的，谢谢，最好在readme里面列一下其它依赖的包。不过我更新之后发现远程调试的问题还是有的(#60)，暂时先回退回去了。

**Comment by cytle** [comment]
@crystoy 好的哈，已经在readme中说明依赖httpie
