### ISSUE TITLE
开发工具内报错

### ISSUE THREAD

**Issue by goldenfreemanchina** [cytle/wechat_web_devtools#75]
开发工具内报错，虽然可以打开，但是始终这样。因为wine的版本？？？
Ubuntu 17.10.1 64bit
wine-2.21 (Staging)

报错如下
/home/golden/.config/微信web开发者工具/WeappVendor/wcc.exe: 1: /home/golden/.config/微信web开发者工具/WeappVendor/wcc.exe: MZ����@���: not found
/home/golden/.config/微信web开发者工具/WeappVendor/wcc.exe: 2: /home/golden/.config/微信web开发者工具/WeappVendor/wcc.exe: cannot open .text�.data�0@�.rdata��@�*@@.bssP�: No such file
/home/golden/.config/微信web开发者工具/WeappVendor/wcc.exe: 2: /home/golden/.config/微信web开发者工具/WeappVendor/wcc.exe: �qZ�7�8�: not found
/home/golden/.config/微信web开发者工具/WeappVendor/wcc.exe: 3: /home/golden/.config/微信web开发者工具/WeappVendor/wcc.exe: Syntax error: word unexpected (expecting ")")

![2018-03-08 19-51-35](https://user-images.githubusercontent.com/6322013/37149765-2d5bf7f4-230a-11e8-8173-a3cab5f992c9.png)

**Comment by goldenfreemanchina** [comment]
更换了wine3.0 问题依然...
`The following commands can be used to add the new repository:

    wget https://dl.winehq.org/wine-builds/Release.key
    sudo apt-key add Release.key
    sudo apt-add-repository 'https://dl.winehq.org/wine-builds/ubuntu/'`

**Comment by cytle** [comment]
同 https://github.com/cytle/wechat_web_devtools/issues/56
