### ISSUE TITLE
安装无法生成文件夹

### ISSUE THREAD

**Issue by zzAbel** [cytle/wechat_web_devtools#76]
kill nw
/home/abel/software/wechat_web_devtools-master/bin/replace_weapp_vendor.sh: line 19: kill: (5448) - No such process
Error: 开发者工具未生成文件夹 /home/abel/.config/微信web开发者工具, 可能是权限问题, 请参考项目issue
Fail! Please reinstall
/home/abel/software/wechat_web_devtools-master/bin/install_desktop.sh: line 6: /home/abel/software/wechat_web_devtools-master/dist/wechat_dev_tools.desktop: Not a directory
Error on file "/home/abel/software/wechat_web_devtools-master/dist/wechat_dev_tools.desktop": Not a directory
安装完成

**Comment by zzAbel** [comment]
已解决 nwjs问题

**Comment by railgun20001** [comment]
@zzAbel 遇到了同样的问题，请问是怎么解决的

**Comment by FrankWang1991** [comment]
@zzAbel   您好，想问一下这个问题的具体解决步骤，也是遇到了这个问题。
