### ISSUE TITLE
我想问下我的编译间隔时间是否正常

### ISSUE THREAD

**Issue by hanliuxin5** [cytle/wechat_web_devtools#78]
各位大佬，我每次修改了 wxml 或者 wxss 文件的话，刷新一次要等上3-4秒，大家都是这样的么？
而如果只是修改 js 文件的话，就很快。

**Comment by HanasakiDeng** [comment]
好像是有这个问题存在

**Comment by cytle** [comment]
这个问题是正常的，wxml 和 wxss 分别需要经过wcc和wcsc编译。现在本项目wcc/wcsc是利用wine提供上下文执行wcc.exe/wcsc.exe。这是至今我能得到的最优方法。

如果有源码，倒是可以在linux下重新编译，然而没有。
