### ISSUE TITLE
我想问每次一开这个就每秒几百k的从某些IP下载东西是正常的吗

### ISSUE THREAD

**Issue by Tubao** [cytle/wechat_web_devtools#81]
这几天留意了一下，通常一上午通过这个程序下载的流量达到2-3GB，连接的IP不定，程序关掉之后流量立刻恢复正常。请问，这个是有恶意代码吗

**Comment by cytle** [comment]
😆，百分百保证没有恶意代码，源码就是官方工具。

**Comment by Tubao** [comment]
今天专门在windows下用官方的程序试了试，果然还是一直大流量。。。应该是官方的问题
