### ISSUE TITLE
@cytle

### ISSUE THREAD

**Issue by jianjun8421** [cytle/wechat_web_devtools#83]
jianjun8421@ljjAir13Pro:~/.config/微信web开发者工具/WeappVendor/s$ sh ./wcc.exe
./wcc.exe: 1: ./wcc.exe: MZ����@���: not found
./wcc.exe: 2: ./wcc.exe: cannot open .text�.data�0@�.rdata��@�*@@.bssP�: No such file
./wcc.exe: 2: ./wcc.exe: ��qZ�7�
                                    8�: not found
./wcc.exe: 3: ./wcc.exe: Syntax error: word unexpected (expecting ")")

**Comment by imknown** [comment]
锟斤拷...

**Comment by cytle** [comment]
@jianjun8421 老哥 https://github.com/cytle/wechat_web_devtools/issues/56#issuecomment-371999385

**Comment by imknown** [comment]
Try https://github.com/cytle/wechat_web_devtools/blob/master/README.md#wcc-和-wcsc-编译错误 .
