### ISSUE TITLE
打开小程序就死机

### ISSUE THREAD

**Issue by skyday2012** [cytle/wechat_web_devtools#87]
开发者您好，我按照步骤安装好之后，打开程序，登录都没有问题，但是当我选择小程序包开始调试时，系统就死机奔溃了，只能按关机键操作。请问我这边时那块配置错了吗？

**Comment by cytle** [comment]
可能是wine有问题，尝试下https://github.com/cytle/wechat_web_devtools/issues/56#issuecomment-371999385
