### ISSUE TITLE
打开之后错误

### ISSUE THREAD

**Issue by owengaozhen** [cytle/wechat_web_devtools#88]
错误：![image](https://user-images.githubusercontent.com/8510542/38462834-8ea5b658-3b1f-11e8-9af8-9cba2846d7dd.png)
wine版本：
![image](https://user-images.githubusercontent.com/8510542/38462840-a13878be-3b1f-11e8-87e3-69517473d99d.png)

**Comment by ayfickle** [comment]
how to solve this problem ?
