### ISSUE TITLE
升级最新版本2018.4.8后 只看到一个 nw.js窗口 没有看到登陆窗口

### ISSUE THREAD

**Issue by godhelpjun** [cytle/wechat_web_devtools#90]
我的环境 ubuntu 16.04 ,wine-3.0 stable,nodejs 8.9.3,chrome-google Version 65.0.3325.181 (Official Build) (64-bit)
./bin/update_package_nw.sh 升级
当前wechat_v: 1.02.1803210
最新wechat_v: 1.02.1804090
0009:fixme:shell:SHAutoComplete stub
002f:err:menubuilder:convert_to_native_icon error 0x80004005 getting frame 0
002f:err:menubuilder:convert_to_native_icon error 0x88982F04 committing encoder
002f:err:menubuilder:convert_to_native_icon error 0x80004005 getting frame 1
002f:err:menubuilder:convert_to_native_icon error 0x88982F04 committing encoder
0031:err:menubuilder:convert_to_native_icon error 0x80004005 getting frame 0
0031:err:menubuilder:convert_to_native_icon error 0x88982F04 committing encoder
0031:err:menubuilder:convert_to_native_icon error 0x80004005 getting frame 1
0031:err:menubuilder:convert_to_native_icon error 0x88982F04 committing encoder
0009:err:process:create_process 64-bit application L"C:\\Program Files\\Tencent\\\5fae\4fe1web\5f00\53d1\8005\5de5\5177\\\5fae\4fe1web\5f00\53d1\8005\5de5\5177.exe" not supported in 32-bit prefix
/home/adam/.wine/drive_c/Program Files (x86)/Tencent/微信web开发者工具/package.nw
cp: cannot stat '/home/adam/.wine/drive_c/Program Files (x86)/Tencent/微信web开发者工具/package.nw': No such file or directory
ls: cannot access '/home/adam/wxdt/package.nw/js/*.js': No such file or directory
sed: no input files
ln: failed to create symbolic link '/home/adam/wxdt/package.nw/node_modules/node-sync-ipc': No such file or directory
ln: failed to access '/home/adam/wxdt/package.nw/js/vendor/wcc.exe': No such file or directory
ln: failed to access '/home/adam/wxdt/package.nw/js/vendor/wcsc.exe': No such file or directory
安装完成
wechat_v: 1.02.1804090

./bin/wxdt 出现下面提示

[19870:19904:0409/211847.550094:ERROR:data_store_impl.cc(131)] Failed to open Data Reduction Proxy DB: 3
[19870:19870:0409/211847.570015:ERROR:desktop_window_tree_host_x11.cc(1159)] Not implemented reached in virtual void views::DesktopWindowTreeHostX11::InitModalType(ui::ModalType)
[19908:19908:0409/211847.727792:ERROR:sandbox_linux.cc(346)] InitializeSandbox() called with multiple threads in process gpu-process.
尝试过下面操作
find ~/.config/google-chrome -name LOCK -delete
也无效果
再试了一下 好像它下载的是64bit的 路径不对
不知道有没有32位的

**Comment by godhelpjun** [comment]
再试了一下 好像它下载的是64bit的 路径不对
不知道有没有32位的

**Comment by cytle** [comment]
更新下载开发者工具是64位的。如果你是64的机子，可以创建一个64位`wine`环境再试一下。如果是32位机子，把`bin/update_package_nw.sh`中*x64*都改为*ia32*试下。

**Comment by imknown** [comment]
建议安装最新 wine-amd64 3.5, 更新了一下 没问题.

**Comment by wsniper** [comment]
误导大家了，不好意思:P
我在win下测试时时新建了一个临时项目。当时没有在picker中设置value属性，所以没问题。
我把ubuntu下的项目拷到win下，就复现问题了。
----------------------------------------------
其实是我自己的错：
picker中的value属性，我把选项数组的名称写错一个字母:p
不过，话说回来。 这个value属性到底啥用？去掉他也不影响。
但是，加上他的话。千万别在 bindcolumnchange回调中修改他的值。会导致递归调用。
