### ISSUE TITLE
请问支持wepy框架么？

### ISSUE THREAD

**Issue by seaguest** [cytle/wechat_web_devtools#97]
我打开项目之后，提示“无法打开此类文件”，有什么解决办法吗？

**Comment by cytle** [comment]
你指的应该是编辑器不能打开`.wpy`文件。

我也在使用`wepy`框架开发项目，一般用`vscode`开发，开发者工具只用来运行`wepy`编译后的文件（`dist`目录）。

**Comment by seaguest** [comment]
@cytle
谢谢
