### ISSUE TITLE
picker组件的bindcolumnchange 好像有bug

### ISSUE THREAD

**Issue by wsniper** [cytle/wechat_web_devtools#99]
以下问题在ubuntu上出现。在win10 64位 开发环境也升级到了最新版，没有这个问题，columnchange事件可正常触发
不知是nw的问题还是微信工具的问题

**os:** ubuntu 16.04 LTS
**测试手机：** 红米3
开发工具相关： nwjs等全部在今天（2018/04/15）升级到了最新
**现象：**
手机和开发工具都是如下现象：
picker  model=“multiSelector"
放在自定义组件中，在page中引用该自定义组件(直接在Page使用picker也是如此)。

**点击弹出选择界面后**
鼠标在移出选项列（应该是触发了该选项列的类似mouseout事件）则会报错如下：
下面的 property '0'/'1'/'2'是选项列的序号(多次实验证实）

> 
> Sun Apr 15 2018 11:15:48 GMT+0800 (CST) 渲染层错误
> VM303:2 TypeError: Cannot read property '0' of null
> 
> Sun Apr 15 2018 11:15:48 GMT+0800 (CST) 渲染层错误
> VM303:2 TypeError: Cannot read property '1' of null
> 
> Sun Apr 15 2018 11:15:48 GMT+0800 (CST) 渲染层错误
> VM303:2 TypeError: Cannot read property '2' of null

**且：**
绑定的选项值变动监听事件： bindcolumnchange 不触发（bindchange正常触发）。
但是，当点击”确定“之后再打开这个selector不在报错，且bindcolumnchange正常触发。

我猜可能picker组件内部监听了类似mouseout的事件，但是该事件对象需要的值应该是选择后的结果数组，即：bindchange事件的e.detail中的对象。

**Comment by cytle** [comment]
https://github.com/cytle/wechat_web_devtools/issues/90
